import { farmDefTypes } from '@plentyag/core/src/farm-def';

const ROOT = 'root';
export const root: farmDefTypes.FarmDefRoot = {
  id: ROOT,
  kind: ROOT,
  path: '/',
  name: ROOT,
  properties: {},
  sites: {
    LAX1: {
      country: 'United States',
      address: 'TODO',
      kind: 'site',
      timezone: 'America/Los_Angeles',
      path: 'sites/LAX1',
      name: 'LAX1',
      id: 'aa0d43c7-9b68-4f9d-bb1e-edd607fade17',
      properties: {},
      areas: {},
    },
    SSF2: {
      country: 'United States',
      address: '570 Eccles Ave, South San Francisco, CA 94080',
      kind: 'site',
      timezone: 'America/Los_Angeles',
      path: 'sites/SSF2',
      name: 'SSF2',
      id: 'cacbd544-6143-48c3-8a72-f2d09bc2fbb7',
      properties: {},
      areas: {
        Seeding: {
          kind: 'area',
          path: 'sites/SSF2/areas/Seeding',
          name: 'Seeding',
          id: '7dbeed4f-d1a0-4cfb-b41b-86e463017cf6',
          lines: {
            TraySeeding: {
              kind: 'line',
              path: 'sites/SSF2/areas/Seeding/lines/TraySeeding',
              name: 'TraySeeding',
              id: '171537c0-f98d-4ca7-a5fb-6b5cb1771e66',
              properties: {
                farmCode: 'TIGRIS',
              },
              deviceLocations: {
                Camera: {
                  ref: '171537c0-f98d-4ca7-a5fb-6b5cb1771e66:deviceLocation-Camera',
                  kind: 'deviceLocation',
                  name: 'Camera',
                  path: 'sites/SSF2/areas/Seeding/lines/TraySeeding/deviceLocations/Camera',
                  class: 'Camera',
                  mappings: [],
                  parentId: '171537c0-f98d-4ca7-a5fb-6b5cb1771e66',
                  interfaces: {},
                  parentPath: 'sites/SSF2/areas/Seeding/lines/TraySeeding',
                  properties: {},
                  deviceTypes: ['BaslerACA402429uc'],
                  placedDeviceId: null,
                  description: '',
                  isGroup: false,
                },
                Camera2: {
                  ref: '171537c0-f98d-4ca7-a5fb-6b5cb1771e66:deviceLocation-Camera2',
                  kind: 'deviceLocation',
                  name: 'Camera',
                  path: 'sites/SSF2/areas/Seeding/lines/TraySeeding/deviceLocations/Camera2',
                  class: 'Camera',
                  mappings: [],
                  parentId: '171537c0-f98d-4ca7-a5fb-6b5cb1771e66',
                  interfaces: {},
                  parentPath: 'sites/SSF2/areas/Seeding/lines/TraySeeding',
                  properties: {},
                  deviceTypes: ['BaslerACA308816gc'],
                  placedDeviceId: null,
                  description: '',
                  isGroup: false,
                },
                Camera3: {
                  ref: '171537c0-f98d-4ca7-a5fb-6b5cb1771e66:deviceLocation-Camera3',
                  kind: 'deviceLocation',
                  name: 'Camera',
                  path: 'sites/SSF2/areas/Seeding/lines/TraySeeding/deviceLocations/Camera3',
                  class: 'Camera',
                  mappings: [],
                  parentId: '171537c0-f98d-4ca7-a5fb-6b5cb1771e66',
                  interfaces: {},
                  parentPath: 'sites/SSF2/areas/Seeding/lines/TraySeeding',
                  properties: {},
                  deviceTypes: ['BaslerACA308816gc'],
                  placedDeviceId: 'd09b8179-464d-4aa4-952b-5caa934536b7',
                  description: '',
                  isGroup: false,
                },
              },
            },
          },
          properties: {
            farmCode: 'TIGRIS',
          },
          scheduleDefinitions: {
            ThermalHumidity: {
              ref: 'cacbd544-6143-48c3-8a72-f2d09bc2fbb7:schedule-ThermalHumidity',
              name: 'ThermalHumidity',
              kind: 'scheduleDefinition',
              path: 'sites/SSF2/areas/Seeding/scheduleDefinitions/ThermalHumidity',
              class: 'ScheduleDefinition',
              parentPath: 'sites/SSF2/areas/Seeding',
              description: 'Controls the humdity',
              properties: {},
              action: {
                supportedKeys: [],
                supportedValues: { from: 0, to: 100 },
                measurementType: 'RELATIVE_HUMIDITY',
              },
              observationSources: [],
            },
            ThermalTemperature: {
              ref: 'cacbd544-6143-48c3-8a72-f2d09bc2fbb7:schedule-ThermalTemperature',
              name: 'ThermalTemperature',
              kind: 'scheduleDefinition',
              path: 'sites/SSF2/areas/Seeding/scheduleDefinitions/ThermalTemperature',
              class: 'ScheduleDefinition',
              parentPath: 'sites/SSF2/areas/Seeding',
              description: 'Controls the temperature',
              properties: {},
              action: {
                supportedKeys: [],
                supportedValues: { from: 0, to: 100 },
                measurementType: 'TEMPERATURE',
              },
              observationSources: [],
            },
          },
        },
        VerticalGrow: {
          kind: 'area',
          path: 'sites/SSF2/areas/VerticalGrow',
          name: 'VerticalGrow',
          id: 'ab6e72fe-7d7c-4f2f-aa06-59d9afd2c0be',
          properties: {
            farmCode: 'TIGRIS',
          },
          lines: {
            GrowRoom: {
              id: 'bdcf2f72-d714-4ae3-862b-2f39cb5469e0',
              kind: 'line',
              name: 'GrowRoom',
              path: 'sites/SSF2/areas/VerticalGrow/lines/GrowRoom',
              properties: {
                farmCode: 'TIGRIS',
              },
              machines: {
                Nutrient2: {
                  name: 'Nutrient2',
                  kind: 'machine',
                  path: 'sites/SSF2/areas/VerticalGrow/lines/GrowRoom/machines/Nutrient2',
                  id: 'b621935c-d78c-4d20-9f60-86e06fd71380',
                  displayName: 'Nutrient2',
                  class: 'NutrientSkid',
                  properties: {},
                },
                GrowLane1: {
                  id: '32d60718-2753-4b35-b67c-58fcb88422e8',
                  kind: 'machine',
                  name: 'GrowLane1',
                  path: 'sites/SSF2/areas/VerticalGrow/lines/GrowRoom/machines/GrowLane1',
                  properties: {},
                  containerLocations: {
                    T2: {
                      ref: '32d60718-2753-4b35-b67c-58fcb88422e8:containerLocation-T2',
                      kind: 'containerLocation',
                      name: 'T2',
                      path: 'sites/SSF2/areas/VerticalGrow/lines/GrowRoom/machines/GrowLane1/containerLocations/T2',
                      class: 'TowerIndex',
                      index: 2,
                      parentId: '32d60718-2753-4b35-b67c-58fcb88422e8',
                      parentPath: 'sites/SSF2/areas/VerticalGrow/lines/GrowRoom/machines/GrowLane1',
                      properties: {},
                      containerTypes: ['Tower'],
                    },
                    T1: {
                      ref: '32d60718-2753-4b35-b67c-58fcb88422e8:containerLocation-T1',
                      kind: 'containerLocation',
                      name: 'T1',
                      path: 'sites/SSF2/areas/VerticalGrow/lines/GrowRoom/machines/GrowLane1/containerLocations/T1',
                      class: 'TowerIndex',
                      index: 1,
                      parentId: '32d60718-2753-4b35-b67c-58fcb88422e8',
                      parentPath: 'sites/SSF2/areas/VerticalGrow/lines/GrowRoom/machines/GrowLane1',
                      properties: {},
                      containerTypes: ['Tower'],
                    },
                  },
                  deviceLocations: {
                    SprinkleGroup: {
                      name: 'SprinkleGroup',
                      kind: 'deviceLocation',
                      description: '',
                      path: 'sites/SSF2/areas/VerticalGrow/lines/GrowRoom/machines/GrowLane1/deviceLocations/SprinkleGroup',
                      ref: '32d60718-2753-4b35-b67c-58fcb88422e8:deviceLocation-SprinkleGroup',
                      class: 'TestSprinkle',
                      parentId: '32d60718-2753-4b35-b67c-58fcb88422e8',
                      parentPath: 'sites/SSF2/areas/VerticalGrow/lines/GrowRoom/machines/GrowLane1',
                      properties: {},
                      deviceTypes: ['Sprinkle2FIR', 'Sprinkle2Base', 'Sprinkle2CO2'],
                      mappings: [],
                      interfaces: {},
                      isGroup: true,
                      locations: {
                        SprinkleSp1p1: {
                          name: 'SprinkleSp1p1',
                          kind: 'childDeviceLocation',
                          path: 'sites/SSF2/areas/VerticalGrow/lines/GrowRoom/machines/GrowLane1/deviceLocations/SprinkleGroup/locations/SprinkleSp1p1',
                          description: 'SprinkleSp1p1 device location',
                          ref: '32d60718-2753-4b35-b67c-58fcb88422e8:deviceLocation-SprinkleGroup:SprinkleSp1p1',
                          class: 'TestItem',
                          parentRef: '32d60718-2753-4b35-b67c-58fcb88422e8:deviceLocation-SprinkleGroup',
                          parentPath:
                            'sites/SSF2/areas/VerticalGrow/lines/GrowRoom/machines/GrowLane1/deviceLocations/SprinkleGroup',
                          properties: {},
                          mappings: [],
                        },
                        SprinkleSp1p2: {
                          name: 'SprinkleSp1p2',
                          kind: 'childDeviceLocation',
                          path: 'sites/SSF2/areas/VerticalGrow/lines/GrowRoom/machines/GrowLane1/deviceLocations/SprinkleGroup/locations/SprinkleSp1p2',
                          description: 'SprinkleSp1p2 device location',
                          ref: '32d60718-2753-4b35-b67c-58fcb88422e8:deviceLocation-SprinkleGroup:SprinkleSp1p2',
                          class: 'TestItem',
                          parentRef: '32d60718-2753-4b35-b67c-58fcb88422e8:deviceLocation-SprinkleGroup',
                          parentPath:
                            'sites/SSF2/areas/VerticalGrow/lines/GrowRoom/machines/GrowLane1/deviceLocations/SprinkleGroup',
                          properties: {},
                          mappings: [],
                        },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
      deviceLocations: {
        Camera: {
          ref: 'cacbd544-6143-48c3-8a72-f2d09bc2fbb7:deviceLocation-Camera',
          kind: 'deviceLocation',
          name: 'Camera',
          path: 'sites/SSF2/deviceLocations/Camera',
          class: 'Camera',
          mappings: [],
          parentId: 'cacbd544-6143-48c3-8a72-f2d09bc2fbb7',
          interfaces: {},
          parentPath: 'sites/SSF2',
          properties: {},
          deviceTypes: ['BaslerACA402429uc'],
          placedDeviceId: null,
          description: '',
          isGroup: false,
        },
      },
      farms: {
        Tigris: {
          id: '0ece1479-2e40-458b-9b17-154f11270006',
          kind: 'farm',
          name: 'Tigris',
          path: 'sites/SSF2/farms/Tigris',
          class: 'TigrisFarm',
          properties: {},
          displayName: 'Tigris',
          deviceLocations: {},
          workCenters: {},
        },
      },
    },
    LAR1: {
      country: 'United States',
      address: '1461 Commerce Dr, Laramie, WY 82070',
      kind: 'site',
      timezone: 'America/Denver',
      path: 'sites/LAR1',
      name: 'LAR1',
      id: '1b513368-80fc-492e-abbb-2ef6bdd14ffa',
      properties: {},
      areas: {},
    },
  },
};
