import { FarmDefCrop, FarmDefSku } from '@plentyag/core/src/farm-def/types';

export const mockCrops: FarmDefCrop[] = [
  {
    displayName: 'Spring Twist - SPT - coir',
    path: 'crops/SPT',
    description: 'Spring Twist Blend: a blend of Green Forest, Cristabel, MSX Red Oak and Amara',
    name: 'SPT',
    commonName: 'Spring Twist',
    cultivar: null,
    media: 'coir',
    displayAbbreviation: 'SPT',
    seedPartNumbers: [],
    cropTypeName: 'LeafyGreens',
    childCrops: [
      {
        defaultCropName: 'GRC',
        allowedCropNames: ['GRC'],
        minRatio: 0.3,
        maxRatio: 0.4,
        targetRatio: 0.35,
      },
      {
        defaultCropName: 'MSX',
        allowedCropNames: ['MSX', 'MSX:NPI'],
        minRatio: 0.1,
        maxRatio: 0.2,
        targetRatio: 0.15,
      },
    ],
    properties: {},
    isSeedable: false,
  },
  {
    displayName: 'Spring Mix - SMB - coir',
    path: 'crops/SMB',
    description: 'Spring Mix Blend: a blend of Green Forest, Cristabel and MSX Red Oak',
    name: 'SMB',
    commonName: 'Spring Mix',
    cultivar: null,
    media: 'coir',
    displayAbbreviation: 'SMB',
    seedPartNumbers: [],
    cropTypeName: 'LeafyGreens',
    childCrops: [
      {
        defaultCropName: 'CRC',
        allowedCropNames: ['CRC'],
        minRatio: 0.3,
        maxRatio: 0.4,
        targetRatio: 0.33,
      },
      {
        defaultCropName: 'MSX',
        allowedCropNames: ['MSX', 'MSX:NPI'],
        minRatio: 0.3,
        maxRatio: 0.4,
        targetRatio: 0.33,
      },
    ],
    properties: {},
    isSeedable: false,
  },
];

export const mockSkus: FarmDefSku[] = [
  {
    displayAbbreviation: 'B11Clamshell4o5oz',
    displayName: 'Baby Kale Clamshell 4.5oz',
    path: 'skus/B11Clamshell4o5oz',
    name: 'B11Clamshell4o5oz',
    kind: 'sku',
    description: null,
    netsuiteItem: '5-004-0001-04',
    gtin: '00810567030415',
    productName: 'Baby Kale',
    skuTypeName: 'Clamshell4o5oz',
    packagingLotCropCode: 'B11',
    defaultCropName: 'B11',
    allowedCropNames: ['B11', 'WHC'],
    labelPrimaryColor: '#542E8E',
    labelSecondaryColor: '#FED141',
    internalExpirationDays: 4,
    externalExpirationDays: 10,
    childSkuName: null,
    properties: {
      empty: true,
      property1: {},
      property2: {},
    },
    brandTypeName: 'Plenty',
    productWeightOz: 4,
  },
  {
    displayAbbreviation: 'CRSCase6Clamshell4o5oz',
    displayName: 'Crispy Lettuce 6ct Case of Clamshells 4.5oz',
    path: 'skus/CRSCase6Clamshell4o5oz',
    name: 'CRSCase6Clamshell4o5oz',
    kind: 'sku',
    description: null,
    netsuiteItem: '5-007-0004-06',
    gtin: '10810567030665',
    productName: 'Crispy Lettuce',
    skuTypeName: 'Case6Clamshell4o5oz',
    packagingLotCropCode: 'CRS',
    defaultCropName: 'CRS',
    allowedCropNames: ['CRS', 'CRC'],
    labelPrimaryColor: '#B5E3D8',
    labelSecondaryColor: '#500878',
    internalExpirationDays: 5,
    externalExpirationDays: 14,
    childSkuName: 'CrsClamshell4o5oz',
    properties: {
      empty: true,
      property1: {},
      property2: {},
    },
    brandTypeName: 'Plenty',
    caseQuantityPerPallet: 4,
  },
  {
    displayAbbreviation: 'B20Bulk1lb',
    displayName: 'Baby Arugula Bulk 1lb',
    path: 'skus/B20Bulk1lb',
    name: 'B20Bulk1lb',
    kind: 'sku',
    description: null,
    netsuiteItem: '5-005-0002-01',
    gtin: '90810567030593',
    productName: 'Baby Arugula',
    skuTypeName: 'Bulk1lb',
    packagingLotCropCode: 'B20',
    defaultCropName: 'B20',
    allowedCropNames: ['BAC', 'B20'],
    labelPrimaryColor: '',
    labelSecondaryColor: '',
    internalExpirationDays: 4,
    externalExpirationDays: 11,
    childSkuName: null,
    properties: {},
    productWeightOz: 16,
  },
];
