export const mockOverrideRoutingTableActionModel: ProdActions.ActionModel = {
  actionType: 'request',
  description:
    'Sets the routing table used to automatically route carriers (gated by the routing_path_override_enabled flag in the SetTransferConveyanceDefaultBehaviorFeatureFlags request)',
  fields: [
    {
      displayName: 'Rule 1 From',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'The ID of Destination from which the Tower should be moved.',
              example: [],
              values: [
                'GR1-1A',
                'GR1-1B',
                'GR1-2A',
                'GR1-2B',
                'GR1-3A',
                'GR1-3B',
                'GR1-4A',
                'GR1-4B',
                'GR2-1A',
                'GR2-1B',
                'GR2-2A',
                'GR2-2B',
                'GR2-3A',
                'GR2-3B',
                'GR2-4A',
                'GR2-4B',
                'GR3-1A',
                'GR3-1B',
                'GR3-2A',
                'GR3-2B',
                'GR3-3A',
                'GR3-3B',
                'GR3-4A',
                'GR3-4B',
                'GR4-1A',
                'GR4-1B',
                'GR4-2A',
                'GR4-2B',
                'GR4-3A',
                'GR4-3B',
                'GR4-4A',
                'GR4-4B',
                'GR5-1A',
                'GR5-1B',
                'GR5-2A',
                'GR5-2B',
                'GR5-3A',
                'GR5-3B',
                'GR5-4A',
                'GR5-4B',
                'GR6-1A',
                'GR6-1B',
                'GR6-2A',
                'GR6-2B',
                'GR6-3A',
                'GR6-3B',
                'GR6-4A',
                'GR6-4B',
                'maintenance',
                'aux-buffer-1',
                'aux-buffer-2',
                'pre-inspection',
                'inspection',
                'pre-harvest-1',
                'pre-harvest-2',
                'empty-carrier-buffer',
                'laydown-robot',
                'cutagain-robot',
                'seedling-buffer',
                'cutagain-buffer',
              ],
            },
            rules: {
              string: {
                pattern:
                  '^(GR[123456]-[1-4][AB]|maintenance|aux-buffer-1|aux-buffer-2|pre-inspection|inspection|pre-harvest-1|pre-harvest-2|empty-carrier-buffer|laydown-robot|cutagain-robot|seedling-buffer|cutagain-buffer)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_1_from',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.ValidLaxSourceForOverrideRoutingTable',
    },
    {
      displayName: 'Rule 1 Condition',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description:
                "Determines how a LAX tower carrier routing rule to move a carrier is triggered; currently either WAIT_FOR_CARRIER_FULL_BEFORE_MOVING or WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING (i.e. routing is triggered either when a carrier at a location has a tower, or when it doesn't have a tower (but can't be both)).",
              example: [],
              values: ['WAIT_FOR_CARRIER_FULL_BEFORE_MOVING', 'WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING'],
            },
            rules: {
              string: {
                pattern: '^(WAIT_FOR_CARRIER_FULL_BEFORE_MOVING|WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_1_condition',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.LaxTowerCarrierAutoRoutingCondition',
    },
    {
      displayName: 'Rule 1 To',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'The ID of Destination from which the Tower should be moved.',
              example: [],
              values: [
                'GR1-1A',
                'GR1-1B',
                'GR1-2A',
                'GR1-2B',
                'GR1-3A',
                'GR1-3B',
                'GR1-4A',
                'GR1-4B',
                'GR2-1A',
                'GR2-1B',
                'GR2-2A',
                'GR2-2B',
                'GR2-3A',
                'GR2-3B',
                'GR2-4A',
                'GR2-4B',
                'GR3-1A',
                'GR3-1B',
                'GR3-2A',
                'GR3-2B',
                'GR3-3A',
                'GR3-3B',
                'GR3-4A',
                'GR3-4B',
                'GR4-1A',
                'GR4-1B',
                'GR4-2A',
                'GR4-2B',
                'GR4-3A',
                'GR4-3B',
                'GR4-4A',
                'GR4-4B',
                'GR5-1A',
                'GR5-1B',
                'GR5-2A',
                'GR5-2B',
                'GR5-3A',
                'GR5-3B',
                'GR5-4A',
                'GR5-4B',
                'GR6-1A',
                'GR6-1B',
                'GR6-2A',
                'GR6-2B',
                'GR6-3A',
                'GR6-3B',
                'GR6-4A',
                'GR6-4B',
                'maintenance',
                'aux-buffer-1',
                'aux-buffer-2',
                'pre-inspection',
                'inspection',
                'pre-harvest-1',
                'pre-harvest-2',
                'empty-carrier-buffer',
                'laydown-robot',
                'cutagain-robot',
                'pickup-robot',
                'seedling-buffer',
                'cutagain-buffer',
              ],
            },
            rules: {
              string: {
                pattern:
                  '^(GR[123456]-[1-4][AB]|maintenance|aux-buffer-1|aux-buffer-2|pre-inspection|inspection|pre-harvest-1|pre-harvest-2|empty-carrier-buffer|laydown-robot|cutagain-robot|pickup-robot|seedling-buffer|cutagain-buffer)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_1_to',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.LaxCarrierDestination',
    },
    {
      displayName: 'Rule 2 From',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'The ID of Destination from which the Tower should be moved.',
              example: [],
              values: [
                'GR1-1A',
                'GR1-1B',
                'GR1-2A',
                'GR1-2B',
                'GR1-3A',
                'GR1-3B',
                'GR1-4A',
                'GR1-4B',
                'GR2-1A',
                'GR2-1B',
                'GR2-2A',
                'GR2-2B',
                'GR2-3A',
                'GR2-3B',
                'GR2-4A',
                'GR2-4B',
                'GR3-1A',
                'GR3-1B',
                'GR3-2A',
                'GR3-2B',
                'GR3-3A',
                'GR3-3B',
                'GR3-4A',
                'GR3-4B',
                'GR4-1A',
                'GR4-1B',
                'GR4-2A',
                'GR4-2B',
                'GR4-3A',
                'GR4-3B',
                'GR4-4A',
                'GR4-4B',
                'GR5-1A',
                'GR5-1B',
                'GR5-2A',
                'GR5-2B',
                'GR5-3A',
                'GR5-3B',
                'GR5-4A',
                'GR5-4B',
                'GR6-1A',
                'GR6-1B',
                'GR6-2A',
                'GR6-2B',
                'GR6-3A',
                'GR6-3B',
                'GR6-4A',
                'GR6-4B',
                'maintenance',
                'aux-buffer-1',
                'aux-buffer-2',
                'pre-inspection',
                'inspection',
                'pre-harvest-1',
                'pre-harvest-2',
                'empty-carrier-buffer',
                'laydown-robot',
                'cutagain-robot',
                'seedling-buffer',
                'cutagain-buffer',
              ],
            },
            rules: {
              string: {
                pattern:
                  '^(GR[123456]-[1-4][AB]|maintenance|aux-buffer-1|aux-buffer-2|pre-inspection|inspection|pre-harvest-1|pre-harvest-2|empty-carrier-buffer|laydown-robot|cutagain-robot|seedling-buffer|cutagain-buffer)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_2_from',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.ValidLaxSourceForOverrideRoutingTable',
    },
    {
      displayName: 'Rule 2 Condition',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description:
                "Determines how a LAX tower carrier routing rule to move a carrier is triggered; currently either WAIT_FOR_CARRIER_FULL_BEFORE_MOVING or WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING (i.e. routing is triggered either when a carrier at a location has a tower, or when it doesn't have a tower (but can't be both)).",
              example: [],
              values: ['WAIT_FOR_CARRIER_FULL_BEFORE_MOVING', 'WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING'],
            },
            rules: {
              string: {
                pattern: '^(WAIT_FOR_CARRIER_FULL_BEFORE_MOVING|WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_2_condition',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.LaxTowerCarrierAutoRoutingCondition',
    },
    {
      displayName: 'Rule 2 To',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'The ID of Destination from which the Tower should be moved.',
              example: [],
              values: [
                'GR1-1A',
                'GR1-1B',
                'GR1-2A',
                'GR1-2B',
                'GR1-3A',
                'GR1-3B',
                'GR1-4A',
                'GR1-4B',
                'GR2-1A',
                'GR2-1B',
                'GR2-2A',
                'GR2-2B',
                'GR2-3A',
                'GR2-3B',
                'GR2-4A',
                'GR2-4B',
                'GR3-1A',
                'GR3-1B',
                'GR3-2A',
                'GR3-2B',
                'GR3-3A',
                'GR3-3B',
                'GR3-4A',
                'GR3-4B',
                'GR4-1A',
                'GR4-1B',
                'GR4-2A',
                'GR4-2B',
                'GR4-3A',
                'GR4-3B',
                'GR4-4A',
                'GR4-4B',
                'GR5-1A',
                'GR5-1B',
                'GR5-2A',
                'GR5-2B',
                'GR5-3A',
                'GR5-3B',
                'GR5-4A',
                'GR5-4B',
                'GR6-1A',
                'GR6-1B',
                'GR6-2A',
                'GR6-2B',
                'GR6-3A',
                'GR6-3B',
                'GR6-4A',
                'GR6-4B',
                'maintenance',
                'aux-buffer-1',
                'aux-buffer-2',
                'pre-inspection',
                'inspection',
                'pre-harvest-1',
                'pre-harvest-2',
                'empty-carrier-buffer',
                'laydown-robot',
                'cutagain-robot',
                'pickup-robot',
                'seedling-buffer',
                'cutagain-buffer',
              ],
            },
            rules: {
              string: {
                pattern:
                  '^(GR[123456]-[1-4][AB]|maintenance|aux-buffer-1|aux-buffer-2|pre-inspection|inspection|pre-harvest-1|pre-harvest-2|empty-carrier-buffer|laydown-robot|cutagain-robot|pickup-robot|seedling-buffer|cutagain-buffer)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_2_to',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.LaxCarrierDestination',
    },
    {
      displayName: 'Rule 3 From',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'The ID of Destination from which the Tower should be moved.',
              example: [],
              values: [
                'GR1-1A',
                'GR1-1B',
                'GR1-2A',
                'GR1-2B',
                'GR1-3A',
                'GR1-3B',
                'GR1-4A',
                'GR1-4B',
                'GR2-1A',
                'GR2-1B',
                'GR2-2A',
                'GR2-2B',
                'GR2-3A',
                'GR2-3B',
                'GR2-4A',
                'GR2-4B',
                'GR3-1A',
                'GR3-1B',
                'GR3-2A',
                'GR3-2B',
                'GR3-3A',
                'GR3-3B',
                'GR3-4A',
                'GR3-4B',
                'GR4-1A',
                'GR4-1B',
                'GR4-2A',
                'GR4-2B',
                'GR4-3A',
                'GR4-3B',
                'GR4-4A',
                'GR4-4B',
                'GR5-1A',
                'GR5-1B',
                'GR5-2A',
                'GR5-2B',
                'GR5-3A',
                'GR5-3B',
                'GR5-4A',
                'GR5-4B',
                'GR6-1A',
                'GR6-1B',
                'GR6-2A',
                'GR6-2B',
                'GR6-3A',
                'GR6-3B',
                'GR6-4A',
                'GR6-4B',
                'maintenance',
                'aux-buffer-1',
                'aux-buffer-2',
                'pre-inspection',
                'inspection',
                'pre-harvest-1',
                'pre-harvest-2',
                'empty-carrier-buffer',
                'laydown-robot',
                'cutagain-robot',
                'seedling-buffer',
                'cutagain-buffer',
              ],
            },
            rules: {
              string: {
                pattern:
                  '^(GR[123456]-[1-4][AB]|maintenance|aux-buffer-1|aux-buffer-2|pre-inspection|inspection|pre-harvest-1|pre-harvest-2|empty-carrier-buffer|laydown-robot|cutagain-robot|seedling-buffer|cutagain-buffer)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_3_from',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.ValidLaxSourceForOverrideRoutingTable',
    },
    {
      displayName: 'Rule 3 Condition',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description:
                "Determines how a LAX tower carrier routing rule to move a carrier is triggered; currently either WAIT_FOR_CARRIER_FULL_BEFORE_MOVING or WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING (i.e. routing is triggered either when a carrier at a location has a tower, or when it doesn't have a tower (but can't be both)).",
              example: [],
              values: ['WAIT_FOR_CARRIER_FULL_BEFORE_MOVING', 'WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING'],
            },
            rules: {
              string: {
                pattern: '^(WAIT_FOR_CARRIER_FULL_BEFORE_MOVING|WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_3_condition',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.LaxTowerCarrierAutoRoutingCondition',
    },
    {
      displayName: 'Rule 3 To',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'The ID of Destination from which the Tower should be moved.',
              example: [],
              values: [
                'GR1-1A',
                'GR1-1B',
                'GR1-2A',
                'GR1-2B',
                'GR1-3A',
                'GR1-3B',
                'GR1-4A',
                'GR1-4B',
                'GR2-1A',
                'GR2-1B',
                'GR2-2A',
                'GR2-2B',
                'GR2-3A',
                'GR2-3B',
                'GR2-4A',
                'GR2-4B',
                'GR3-1A',
                'GR3-1B',
                'GR3-2A',
                'GR3-2B',
                'GR3-3A',
                'GR3-3B',
                'GR3-4A',
                'GR3-4B',
                'GR4-1A',
                'GR4-1B',
                'GR4-2A',
                'GR4-2B',
                'GR4-3A',
                'GR4-3B',
                'GR4-4A',
                'GR4-4B',
                'GR5-1A',
                'GR5-1B',
                'GR5-2A',
                'GR5-2B',
                'GR5-3A',
                'GR5-3B',
                'GR5-4A',
                'GR5-4B',
                'GR6-1A',
                'GR6-1B',
                'GR6-2A',
                'GR6-2B',
                'GR6-3A',
                'GR6-3B',
                'GR6-4A',
                'GR6-4B',
                'maintenance',
                'aux-buffer-1',
                'aux-buffer-2',
                'pre-inspection',
                'inspection',
                'pre-harvest-1',
                'pre-harvest-2',
                'empty-carrier-buffer',
                'laydown-robot',
                'cutagain-robot',
                'pickup-robot',
                'seedling-buffer',
                'cutagain-buffer',
              ],
            },
            rules: {
              string: {
                pattern:
                  '^(GR[123456]-[1-4][AB]|maintenance|aux-buffer-1|aux-buffer-2|pre-inspection|inspection|pre-harvest-1|pre-harvest-2|empty-carrier-buffer|laydown-robot|cutagain-robot|pickup-robot|seedling-buffer|cutagain-buffer)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_3_to',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.LaxCarrierDestination',
    },
    {
      displayName: 'Rule 4 From',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'The ID of Destination from which the Tower should be moved.',
              example: [],
              values: [
                'GR1-1A',
                'GR1-1B',
                'GR1-2A',
                'GR1-2B',
                'GR1-3A',
                'GR1-3B',
                'GR1-4A',
                'GR1-4B',
                'GR2-1A',
                'GR2-1B',
                'GR2-2A',
                'GR2-2B',
                'GR2-3A',
                'GR2-3B',
                'GR2-4A',
                'GR2-4B',
                'GR3-1A',
                'GR3-1B',
                'GR3-2A',
                'GR3-2B',
                'GR3-3A',
                'GR3-3B',
                'GR3-4A',
                'GR3-4B',
                'GR4-1A',
                'GR4-1B',
                'GR4-2A',
                'GR4-2B',
                'GR4-3A',
                'GR4-3B',
                'GR4-4A',
                'GR4-4B',
                'GR5-1A',
                'GR5-1B',
                'GR5-2A',
                'GR5-2B',
                'GR5-3A',
                'GR5-3B',
                'GR5-4A',
                'GR5-4B',
                'GR6-1A',
                'GR6-1B',
                'GR6-2A',
                'GR6-2B',
                'GR6-3A',
                'GR6-3B',
                'GR6-4A',
                'GR6-4B',
                'maintenance',
                'aux-buffer-1',
                'aux-buffer-2',
                'pre-inspection',
                'inspection',
                'pre-harvest-1',
                'pre-harvest-2',
                'empty-carrier-buffer',
                'laydown-robot',
                'cutagain-robot',
                'seedling-buffer',
                'cutagain-buffer',
              ],
            },
            rules: {
              string: {
                pattern:
                  '^(GR[123456]-[1-4][AB]|maintenance|aux-buffer-1|aux-buffer-2|pre-inspection|inspection|pre-harvest-1|pre-harvest-2|empty-carrier-buffer|laydown-robot|cutagain-robot|seedling-buffer|cutagain-buffer)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_4_from',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.ValidLaxSourceForOverrideRoutingTable',
    },
    {
      displayName: 'Rule 4 Condition',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description:
                "Determines how a LAX tower carrier routing rule to move a carrier is triggered; currently either WAIT_FOR_CARRIER_FULL_BEFORE_MOVING or WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING (i.e. routing is triggered either when a carrier at a location has a tower, or when it doesn't have a tower (but can't be both)).",
              example: [],
              values: ['WAIT_FOR_CARRIER_FULL_BEFORE_MOVING', 'WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING'],
            },
            rules: {
              string: {
                pattern: '^(WAIT_FOR_CARRIER_FULL_BEFORE_MOVING|WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_4_condition',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.LaxTowerCarrierAutoRoutingCondition',
    },
    {
      displayName: 'Rule 4 To',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'The ID of Destination from which the Tower should be moved.',
              example: [],
              values: [
                'GR1-1A',
                'GR1-1B',
                'GR1-2A',
                'GR1-2B',
                'GR1-3A',
                'GR1-3B',
                'GR1-4A',
                'GR1-4B',
                'GR2-1A',
                'GR2-1B',
                'GR2-2A',
                'GR2-2B',
                'GR2-3A',
                'GR2-3B',
                'GR2-4A',
                'GR2-4B',
                'GR3-1A',
                'GR3-1B',
                'GR3-2A',
                'GR3-2B',
                'GR3-3A',
                'GR3-3B',
                'GR3-4A',
                'GR3-4B',
                'GR4-1A',
                'GR4-1B',
                'GR4-2A',
                'GR4-2B',
                'GR4-3A',
                'GR4-3B',
                'GR4-4A',
                'GR4-4B',
                'GR5-1A',
                'GR5-1B',
                'GR5-2A',
                'GR5-2B',
                'GR5-3A',
                'GR5-3B',
                'GR5-4A',
                'GR5-4B',
                'GR6-1A',
                'GR6-1B',
                'GR6-2A',
                'GR6-2B',
                'GR6-3A',
                'GR6-3B',
                'GR6-4A',
                'GR6-4B',
                'maintenance',
                'aux-buffer-1',
                'aux-buffer-2',
                'pre-inspection',
                'inspection',
                'pre-harvest-1',
                'pre-harvest-2',
                'empty-carrier-buffer',
                'laydown-robot',
                'cutagain-robot',
                'pickup-robot',
                'seedling-buffer',
                'cutagain-buffer',
              ],
            },
            rules: {
              string: {
                pattern:
                  '^(GR[123456]-[1-4][AB]|maintenance|aux-buffer-1|aux-buffer-2|pre-inspection|inspection|pre-harvest-1|pre-harvest-2|empty-carrier-buffer|laydown-robot|cutagain-robot|pickup-robot|seedling-buffer|cutagain-buffer)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_4_to',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.LaxCarrierDestination',
    },
    {
      displayName: 'Rule 5 From',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'The ID of Destination from which the Tower should be moved.',
              example: [],
              values: [
                'GR1-1A',
                'GR1-1B',
                'GR1-2A',
                'GR1-2B',
                'GR1-3A',
                'GR1-3B',
                'GR1-4A',
                'GR1-4B',
                'GR2-1A',
                'GR2-1B',
                'GR2-2A',
                'GR2-2B',
                'GR2-3A',
                'GR2-3B',
                'GR2-4A',
                'GR2-4B',
                'GR3-1A',
                'GR3-1B',
                'GR3-2A',
                'GR3-2B',
                'GR3-3A',
                'GR3-3B',
                'GR3-4A',
                'GR3-4B',
                'GR4-1A',
                'GR4-1B',
                'GR4-2A',
                'GR4-2B',
                'GR4-3A',
                'GR4-3B',
                'GR4-4A',
                'GR4-4B',
                'GR5-1A',
                'GR5-1B',
                'GR5-2A',
                'GR5-2B',
                'GR5-3A',
                'GR5-3B',
                'GR5-4A',
                'GR5-4B',
                'GR6-1A',
                'GR6-1B',
                'GR6-2A',
                'GR6-2B',
                'GR6-3A',
                'GR6-3B',
                'GR6-4A',
                'GR6-4B',
                'maintenance',
                'aux-buffer-1',
                'aux-buffer-2',
                'pre-inspection',
                'inspection',
                'pre-harvest-1',
                'pre-harvest-2',
                'empty-carrier-buffer',
                'laydown-robot',
                'cutagain-robot',
                'seedling-buffer',
                'cutagain-buffer',
              ],
            },
            rules: {
              string: {
                pattern:
                  '^(GR[123456]-[1-4][AB]|maintenance|aux-buffer-1|aux-buffer-2|pre-inspection|inspection|pre-harvest-1|pre-harvest-2|empty-carrier-buffer|laydown-robot|cutagain-robot|seedling-buffer|cutagain-buffer)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_5_from',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.ValidLaxSourceForOverrideRoutingTable',
    },
    {
      displayName: 'Rule 5 Condition',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description:
                "Determines how a LAX tower carrier routing rule to move a carrier is triggered; currently either WAIT_FOR_CARRIER_FULL_BEFORE_MOVING or WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING (i.e. routing is triggered either when a carrier at a location has a tower, or when it doesn't have a tower (but can't be both)).",
              example: [],
              values: ['WAIT_FOR_CARRIER_FULL_BEFORE_MOVING', 'WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING'],
            },
            rules: {
              string: {
                pattern: '^(WAIT_FOR_CARRIER_FULL_BEFORE_MOVING|WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_5_condition',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.LaxTowerCarrierAutoRoutingCondition',
    },
    {
      displayName: 'Rule 5 To',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'The ID of Destination from which the Tower should be moved.',
              example: [],
              values: [
                'GR1-1A',
                'GR1-1B',
                'GR1-2A',
                'GR1-2B',
                'GR1-3A',
                'GR1-3B',
                'GR1-4A',
                'GR1-4B',
                'GR2-1A',
                'GR2-1B',
                'GR2-2A',
                'GR2-2B',
                'GR2-3A',
                'GR2-3B',
                'GR2-4A',
                'GR2-4B',
                'GR3-1A',
                'GR3-1B',
                'GR3-2A',
                'GR3-2B',
                'GR3-3A',
                'GR3-3B',
                'GR3-4A',
                'GR3-4B',
                'GR4-1A',
                'GR4-1B',
                'GR4-2A',
                'GR4-2B',
                'GR4-3A',
                'GR4-3B',
                'GR4-4A',
                'GR4-4B',
                'GR5-1A',
                'GR5-1B',
                'GR5-2A',
                'GR5-2B',
                'GR5-3A',
                'GR5-3B',
                'GR5-4A',
                'GR5-4B',
                'GR6-1A',
                'GR6-1B',
                'GR6-2A',
                'GR6-2B',
                'GR6-3A',
                'GR6-3B',
                'GR6-4A',
                'GR6-4B',
                'maintenance',
                'aux-buffer-1',
                'aux-buffer-2',
                'pre-inspection',
                'inspection',
                'pre-harvest-1',
                'pre-harvest-2',
                'empty-carrier-buffer',
                'laydown-robot',
                'cutagain-robot',
                'pickup-robot',
                'seedling-buffer',
                'cutagain-buffer',
              ],
            },
            rules: {
              string: {
                pattern:
                  '^(GR[123456]-[1-4][AB]|maintenance|aux-buffer-1|aux-buffer-2|pre-inspection|inspection|pre-harvest-1|pre-harvest-2|empty-carrier-buffer|laydown-robot|cutagain-robot|pickup-robot|seedling-buffer|cutagain-buffer)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_5_to',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.LaxCarrierDestination',
    },
    {
      displayName: 'Rule 6 From',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'The ID of Destination from which the Tower should be moved.',
              example: [],
              values: [
                'GR1-1A',
                'GR1-1B',
                'GR1-2A',
                'GR1-2B',
                'GR1-3A',
                'GR1-3B',
                'GR1-4A',
                'GR1-4B',
                'GR2-1A',
                'GR2-1B',
                'GR2-2A',
                'GR2-2B',
                'GR2-3A',
                'GR2-3B',
                'GR2-4A',
                'GR2-4B',
                'GR3-1A',
                'GR3-1B',
                'GR3-2A',
                'GR3-2B',
                'GR3-3A',
                'GR3-3B',
                'GR3-4A',
                'GR3-4B',
                'GR4-1A',
                'GR4-1B',
                'GR4-2A',
                'GR4-2B',
                'GR4-3A',
                'GR4-3B',
                'GR4-4A',
                'GR4-4B',
                'GR5-1A',
                'GR5-1B',
                'GR5-2A',
                'GR5-2B',
                'GR5-3A',
                'GR5-3B',
                'GR5-4A',
                'GR5-4B',
                'GR6-1A',
                'GR6-1B',
                'GR6-2A',
                'GR6-2B',
                'GR6-3A',
                'GR6-3B',
                'GR6-4A',
                'GR6-4B',
                'maintenance',
                'aux-buffer-1',
                'aux-buffer-2',
                'pre-inspection',
                'inspection',
                'pre-harvest-1',
                'pre-harvest-2',
                'empty-carrier-buffer',
                'laydown-robot',
                'cutagain-robot',
                'seedling-buffer',
                'cutagain-buffer',
              ],
            },
            rules: {
              string: {
                pattern:
                  '^(GR[123456]-[1-4][AB]|maintenance|aux-buffer-1|aux-buffer-2|pre-inspection|inspection|pre-harvest-1|pre-harvest-2|empty-carrier-buffer|laydown-robot|cutagain-robot|seedling-buffer|cutagain-buffer)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_6_from',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.ValidLaxSourceForOverrideRoutingTable',
    },
    {
      displayName: 'Rule 6 Condition',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description:
                "Determines how a LAX tower carrier routing rule to move a carrier is triggered; currently either WAIT_FOR_CARRIER_FULL_BEFORE_MOVING or WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING (i.e. routing is triggered either when a carrier at a location has a tower, or when it doesn't have a tower (but can't be both)).",
              example: [],
              values: ['WAIT_FOR_CARRIER_FULL_BEFORE_MOVING', 'WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING'],
            },
            rules: {
              string: {
                pattern: '^(WAIT_FOR_CARRIER_FULL_BEFORE_MOVING|WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_6_condition',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.LaxTowerCarrierAutoRoutingCondition',
    },
    {
      displayName: 'Rule 6 To',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'The ID of Destination from which the Tower should be moved.',
              example: [],
              values: [
                'GR1-1A',
                'GR1-1B',
                'GR1-2A',
                'GR1-2B',
                'GR1-3A',
                'GR1-3B',
                'GR1-4A',
                'GR1-4B',
                'GR2-1A',
                'GR2-1B',
                'GR2-2A',
                'GR2-2B',
                'GR2-3A',
                'GR2-3B',
                'GR2-4A',
                'GR2-4B',
                'GR3-1A',
                'GR3-1B',
                'GR3-2A',
                'GR3-2B',
                'GR3-3A',
                'GR3-3B',
                'GR3-4A',
                'GR3-4B',
                'GR4-1A',
                'GR4-1B',
                'GR4-2A',
                'GR4-2B',
                'GR4-3A',
                'GR4-3B',
                'GR4-4A',
                'GR4-4B',
                'GR5-1A',
                'GR5-1B',
                'GR5-2A',
                'GR5-2B',
                'GR5-3A',
                'GR5-3B',
                'GR5-4A',
                'GR5-4B',
                'GR6-1A',
                'GR6-1B',
                'GR6-2A',
                'GR6-2B',
                'GR6-3A',
                'GR6-3B',
                'GR6-4A',
                'GR6-4B',
                'maintenance',
                'aux-buffer-1',
                'aux-buffer-2',
                'pre-inspection',
                'inspection',
                'pre-harvest-1',
                'pre-harvest-2',
                'empty-carrier-buffer',
                'laydown-robot',
                'cutagain-robot',
                'pickup-robot',
                'seedling-buffer',
                'cutagain-buffer',
              ],
            },
            rules: {
              string: {
                pattern:
                  '^(GR[123456]-[1-4][AB]|maintenance|aux-buffer-1|aux-buffer-2|pre-inspection|inspection|pre-harvest-1|pre-harvest-2|empty-carrier-buffer|laydown-robot|cutagain-robot|pickup-robot|seedling-buffer|cutagain-buffer)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_6_to',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.LaxCarrierDestination',
    },
    {
      displayName: 'Rule 7 From',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'The ID of Destination from which the Tower should be moved.',
              example: [],
              values: [
                'GR1-1A',
                'GR1-1B',
                'GR1-2A',
                'GR1-2B',
                'GR1-3A',
                'GR1-3B',
                'GR1-4A',
                'GR1-4B',
                'GR2-1A',
                'GR2-1B',
                'GR2-2A',
                'GR2-2B',
                'GR2-3A',
                'GR2-3B',
                'GR2-4A',
                'GR2-4B',
                'GR3-1A',
                'GR3-1B',
                'GR3-2A',
                'GR3-2B',
                'GR3-3A',
                'GR3-3B',
                'GR3-4A',
                'GR3-4B',
                'GR4-1A',
                'GR4-1B',
                'GR4-2A',
                'GR4-2B',
                'GR4-3A',
                'GR4-3B',
                'GR4-4A',
                'GR4-4B',
                'GR5-1A',
                'GR5-1B',
                'GR5-2A',
                'GR5-2B',
                'GR5-3A',
                'GR5-3B',
                'GR5-4A',
                'GR5-4B',
                'GR6-1A',
                'GR6-1B',
                'GR6-2A',
                'GR6-2B',
                'GR6-3A',
                'GR6-3B',
                'GR6-4A',
                'GR6-4B',
                'maintenance',
                'aux-buffer-1',
                'aux-buffer-2',
                'pre-inspection',
                'inspection',
                'pre-harvest-1',
                'pre-harvest-2',
                'empty-carrier-buffer',
                'laydown-robot',
                'cutagain-robot',
                'seedling-buffer',
                'cutagain-buffer',
              ],
            },
            rules: {
              string: {
                pattern:
                  '^(GR[123456]-[1-4][AB]|maintenance|aux-buffer-1|aux-buffer-2|pre-inspection|inspection|pre-harvest-1|pre-harvest-2|empty-carrier-buffer|laydown-robot|cutagain-robot|seedling-buffer|cutagain-buffer)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_7_from',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.ValidLaxSourceForOverrideRoutingTable',
    },
    {
      displayName: 'Rule 7 Condition',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description:
                "Determines how a LAX tower carrier routing rule to move a carrier is triggered; currently either WAIT_FOR_CARRIER_FULL_BEFORE_MOVING or WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING (i.e. routing is triggered either when a carrier at a location has a tower, or when it doesn't have a tower (but can't be both)).",
              example: [],
              values: ['WAIT_FOR_CARRIER_FULL_BEFORE_MOVING', 'WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING'],
            },
            rules: {
              string: {
                pattern: '^(WAIT_FOR_CARRIER_FULL_BEFORE_MOVING|WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_7_condition',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.LaxTowerCarrierAutoRoutingCondition',
    },
    {
      displayName: 'Rule 7 To',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'The ID of Destination from which the Tower should be moved.',
              example: [],
              values: [
                'GR1-1A',
                'GR1-1B',
                'GR1-2A',
                'GR1-2B',
                'GR1-3A',
                'GR1-3B',
                'GR1-4A',
                'GR1-4B',
                'GR2-1A',
                'GR2-1B',
                'GR2-2A',
                'GR2-2B',
                'GR2-3A',
                'GR2-3B',
                'GR2-4A',
                'GR2-4B',
                'GR3-1A',
                'GR3-1B',
                'GR3-2A',
                'GR3-2B',
                'GR3-3A',
                'GR3-3B',
                'GR3-4A',
                'GR3-4B',
                'GR4-1A',
                'GR4-1B',
                'GR4-2A',
                'GR4-2B',
                'GR4-3A',
                'GR4-3B',
                'GR4-4A',
                'GR4-4B',
                'GR5-1A',
                'GR5-1B',
                'GR5-2A',
                'GR5-2B',
                'GR5-3A',
                'GR5-3B',
                'GR5-4A',
                'GR5-4B',
                'GR6-1A',
                'GR6-1B',
                'GR6-2A',
                'GR6-2B',
                'GR6-3A',
                'GR6-3B',
                'GR6-4A',
                'GR6-4B',
                'maintenance',
                'aux-buffer-1',
                'aux-buffer-2',
                'pre-inspection',
                'inspection',
                'pre-harvest-1',
                'pre-harvest-2',
                'empty-carrier-buffer',
                'laydown-robot',
                'cutagain-robot',
                'pickup-robot',
                'seedling-buffer',
                'cutagain-buffer',
              ],
            },
            rules: {
              string: {
                pattern:
                  '^(GR[123456]-[1-4][AB]|maintenance|aux-buffer-1|aux-buffer-2|pre-inspection|inspection|pre-harvest-1|pre-harvest-2|empty-carrier-buffer|laydown-robot|cutagain-robot|pickup-robot|seedling-buffer|cutagain-buffer)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_7_to',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.LaxCarrierDestination',
    },
    {
      displayName: 'Rule 8 From',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'The ID of Destination from which the Tower should be moved.',
              example: [],
              values: [
                'GR1-1A',
                'GR1-1B',
                'GR1-2A',
                'GR1-2B',
                'GR1-3A',
                'GR1-3B',
                'GR1-4A',
                'GR1-4B',
                'GR2-1A',
                'GR2-1B',
                'GR2-2A',
                'GR2-2B',
                'GR2-3A',
                'GR2-3B',
                'GR2-4A',
                'GR2-4B',
                'GR3-1A',
                'GR3-1B',
                'GR3-2A',
                'GR3-2B',
                'GR3-3A',
                'GR3-3B',
                'GR3-4A',
                'GR3-4B',
                'GR4-1A',
                'GR4-1B',
                'GR4-2A',
                'GR4-2B',
                'GR4-3A',
                'GR4-3B',
                'GR4-4A',
                'GR4-4B',
                'GR5-1A',
                'GR5-1B',
                'GR5-2A',
                'GR5-2B',
                'GR5-3A',
                'GR5-3B',
                'GR5-4A',
                'GR5-4B',
                'GR6-1A',
                'GR6-1B',
                'GR6-2A',
                'GR6-2B',
                'GR6-3A',
                'GR6-3B',
                'GR6-4A',
                'GR6-4B',
                'maintenance',
                'aux-buffer-1',
                'aux-buffer-2',
                'pre-inspection',
                'inspection',
                'pre-harvest-1',
                'pre-harvest-2',
                'empty-carrier-buffer',
                'laydown-robot',
                'cutagain-robot',
                'seedling-buffer',
                'cutagain-buffer',
              ],
            },
            rules: {
              string: {
                pattern:
                  '^(GR[123456]-[1-4][AB]|maintenance|aux-buffer-1|aux-buffer-2|pre-inspection|inspection|pre-harvest-1|pre-harvest-2|empty-carrier-buffer|laydown-robot|cutagain-robot|seedling-buffer|cutagain-buffer)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_8_from',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.ValidLaxSourceForOverrideRoutingTable',
    },
    {
      displayName: 'Rule 8 Condition',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description:
                "Determines how a LAX tower carrier routing rule to move a carrier is triggered; currently either WAIT_FOR_CARRIER_FULL_BEFORE_MOVING or WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING (i.e. routing is triggered either when a carrier at a location has a tower, or when it doesn't have a tower (but can't be both)).",
              example: [],
              values: ['WAIT_FOR_CARRIER_FULL_BEFORE_MOVING', 'WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING'],
            },
            rules: {
              string: {
                pattern: '^(WAIT_FOR_CARRIER_FULL_BEFORE_MOVING|WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_8_condition',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.LaxTowerCarrierAutoRoutingCondition',
    },
    {
      displayName: 'Rule 8 To',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'The ID of Destination from which the Tower should be moved.',
              example: [],
              values: [
                'GR1-1A',
                'GR1-1B',
                'GR1-2A',
                'GR1-2B',
                'GR1-3A',
                'GR1-3B',
                'GR1-4A',
                'GR1-4B',
                'GR2-1A',
                'GR2-1B',
                'GR2-2A',
                'GR2-2B',
                'GR2-3A',
                'GR2-3B',
                'GR2-4A',
                'GR2-4B',
                'GR3-1A',
                'GR3-1B',
                'GR3-2A',
                'GR3-2B',
                'GR3-3A',
                'GR3-3B',
                'GR3-4A',
                'GR3-4B',
                'GR4-1A',
                'GR4-1B',
                'GR4-2A',
                'GR4-2B',
                'GR4-3A',
                'GR4-3B',
                'GR4-4A',
                'GR4-4B',
                'GR5-1A',
                'GR5-1B',
                'GR5-2A',
                'GR5-2B',
                'GR5-3A',
                'GR5-3B',
                'GR5-4A',
                'GR5-4B',
                'GR6-1A',
                'GR6-1B',
                'GR6-2A',
                'GR6-2B',
                'GR6-3A',
                'GR6-3B',
                'GR6-4A',
                'GR6-4B',
                'maintenance',
                'aux-buffer-1',
                'aux-buffer-2',
                'pre-inspection',
                'inspection',
                'pre-harvest-1',
                'pre-harvest-2',
                'empty-carrier-buffer',
                'laydown-robot',
                'cutagain-robot',
                'pickup-robot',
                'seedling-buffer',
                'cutagain-buffer',
              ],
            },
            rules: {
              string: {
                pattern:
                  '^(GR[123456]-[1-4][AB]|maintenance|aux-buffer-1|aux-buffer-2|pre-inspection|inspection|pre-harvest-1|pre-harvest-2|empty-carrier-buffer|laydown-robot|cutagain-robot|pickup-robot|seedling-buffer|cutagain-buffer)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_8_to',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.LaxCarrierDestination',
    },
    {
      displayName: 'Rule 9 From',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'The ID of Destination from which the Tower should be moved.',
              example: [],
              values: [
                'GR1-1A',
                'GR1-1B',
                'GR1-2A',
                'GR1-2B',
                'GR1-3A',
                'GR1-3B',
                'GR1-4A',
                'GR1-4B',
                'GR2-1A',
                'GR2-1B',
                'GR2-2A',
                'GR2-2B',
                'GR2-3A',
                'GR2-3B',
                'GR2-4A',
                'GR2-4B',
                'GR3-1A',
                'GR3-1B',
                'GR3-2A',
                'GR3-2B',
                'GR3-3A',
                'GR3-3B',
                'GR3-4A',
                'GR3-4B',
                'GR4-1A',
                'GR4-1B',
                'GR4-2A',
                'GR4-2B',
                'GR4-3A',
                'GR4-3B',
                'GR4-4A',
                'GR4-4B',
                'GR5-1A',
                'GR5-1B',
                'GR5-2A',
                'GR5-2B',
                'GR5-3A',
                'GR5-3B',
                'GR5-4A',
                'GR5-4B',
                'GR6-1A',
                'GR6-1B',
                'GR6-2A',
                'GR6-2B',
                'GR6-3A',
                'GR6-3B',
                'GR6-4A',
                'GR6-4B',
                'maintenance',
                'aux-buffer-1',
                'aux-buffer-2',
                'pre-inspection',
                'inspection',
                'pre-harvest-1',
                'pre-harvest-2',
                'empty-carrier-buffer',
                'laydown-robot',
                'cutagain-robot',
                'seedling-buffer',
                'cutagain-buffer',
              ],
            },
            rules: {
              string: {
                pattern:
                  '^(GR[123456]-[1-4][AB]|maintenance|aux-buffer-1|aux-buffer-2|pre-inspection|inspection|pre-harvest-1|pre-harvest-2|empty-carrier-buffer|laydown-robot|cutagain-robot|seedling-buffer|cutagain-buffer)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_9_from',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.ValidLaxSourceForOverrideRoutingTable',
    },
    {
      displayName: 'Rule 9 Condition',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description:
                "Determines how a LAX tower carrier routing rule to move a carrier is triggered; currently either WAIT_FOR_CARRIER_FULL_BEFORE_MOVING or WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING (i.e. routing is triggered either when a carrier at a location has a tower, or when it doesn't have a tower (but can't be both)).",
              example: [],
              values: ['WAIT_FOR_CARRIER_FULL_BEFORE_MOVING', 'WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING'],
            },
            rules: {
              string: {
                pattern: '^(WAIT_FOR_CARRIER_FULL_BEFORE_MOVING|WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_9_condition',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.LaxTowerCarrierAutoRoutingCondition',
    },
    {
      displayName: 'Rule 9 To',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'The ID of Destination from which the Tower should be moved.',
              example: [],
              values: [
                'GR1-1A',
                'GR1-1B',
                'GR1-2A',
                'GR1-2B',
                'GR1-3A',
                'GR1-3B',
                'GR1-4A',
                'GR1-4B',
                'GR2-1A',
                'GR2-1B',
                'GR2-2A',
                'GR2-2B',
                'GR2-3A',
                'GR2-3B',
                'GR2-4A',
                'GR2-4B',
                'GR3-1A',
                'GR3-1B',
                'GR3-2A',
                'GR3-2B',
                'GR3-3A',
                'GR3-3B',
                'GR3-4A',
                'GR3-4B',
                'GR4-1A',
                'GR4-1B',
                'GR4-2A',
                'GR4-2B',
                'GR4-3A',
                'GR4-3B',
                'GR4-4A',
                'GR4-4B',
                'GR5-1A',
                'GR5-1B',
                'GR5-2A',
                'GR5-2B',
                'GR5-3A',
                'GR5-3B',
                'GR5-4A',
                'GR5-4B',
                'GR6-1A',
                'GR6-1B',
                'GR6-2A',
                'GR6-2B',
                'GR6-3A',
                'GR6-3B',
                'GR6-4A',
                'GR6-4B',
                'maintenance',
                'aux-buffer-1',
                'aux-buffer-2',
                'pre-inspection',
                'inspection',
                'pre-harvest-1',
                'pre-harvest-2',
                'empty-carrier-buffer',
                'laydown-robot',
                'cutagain-robot',
                'pickup-robot',
                'seedling-buffer',
                'cutagain-buffer',
              ],
            },
            rules: {
              string: {
                pattern:
                  '^(GR[123456]-[1-4][AB]|maintenance|aux-buffer-1|aux-buffer-2|pre-inspection|inspection|pre-harvest-1|pre-harvest-2|empty-carrier-buffer|laydown-robot|cutagain-robot|pickup-robot|seedling-buffer|cutagain-buffer)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_9_to',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.LaxCarrierDestination',
    },
    {
      displayName: 'Rule 10 From',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'The ID of Destination from which the Tower should be moved.',
              example: [],
              values: [
                'GR1-1A',
                'GR1-1B',
                'GR1-2A',
                'GR1-2B',
                'GR1-3A',
                'GR1-3B',
                'GR1-4A',
                'GR1-4B',
                'GR2-1A',
                'GR2-1B',
                'GR2-2A',
                'GR2-2B',
                'GR2-3A',
                'GR2-3B',
                'GR2-4A',
                'GR2-4B',
                'GR3-1A',
                'GR3-1B',
                'GR3-2A',
                'GR3-2B',
                'GR3-3A',
                'GR3-3B',
                'GR3-4A',
                'GR3-4B',
                'GR4-1A',
                'GR4-1B',
                'GR4-2A',
                'GR4-2B',
                'GR4-3A',
                'GR4-3B',
                'GR4-4A',
                'GR4-4B',
                'GR5-1A',
                'GR5-1B',
                'GR5-2A',
                'GR5-2B',
                'GR5-3A',
                'GR5-3B',
                'GR5-4A',
                'GR5-4B',
                'GR6-1A',
                'GR6-1B',
                'GR6-2A',
                'GR6-2B',
                'GR6-3A',
                'GR6-3B',
                'GR6-4A',
                'GR6-4B',
                'maintenance',
                'aux-buffer-1',
                'aux-buffer-2',
                'pre-inspection',
                'inspection',
                'pre-harvest-1',
                'pre-harvest-2',
                'empty-carrier-buffer',
                'laydown-robot',
                'cutagain-robot',
                'seedling-buffer',
                'cutagain-buffer',
              ],
            },
            rules: {
              string: {
                pattern:
                  '^(GR[123456]-[1-4][AB]|maintenance|aux-buffer-1|aux-buffer-2|pre-inspection|inspection|pre-harvest-1|pre-harvest-2|empty-carrier-buffer|laydown-robot|cutagain-robot|seedling-buffer|cutagain-buffer)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_10_from',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.ValidLaxSourceForOverrideRoutingTable',
    },
    {
      displayName: 'Rule 10 Condition',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description:
                "Determines how a LAX tower carrier routing rule to move a carrier is triggered; currently either WAIT_FOR_CARRIER_FULL_BEFORE_MOVING or WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING (i.e. routing is triggered either when a carrier at a location has a tower, or when it doesn't have a tower (but can't be both)).",
              example: [],
              values: ['WAIT_FOR_CARRIER_FULL_BEFORE_MOVING', 'WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING'],
            },
            rules: {
              string: {
                pattern: '^(WAIT_FOR_CARRIER_FULL_BEFORE_MOVING|WAIT_FOR_CARRIER_EMPTY_BEFORE_MOVING)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_10_condition',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.LaxTowerCarrierAutoRoutingCondition',
    },
    {
      displayName: 'Rule 10 To',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'The ID of Destination from which the Tower should be moved.',
              example: [],
              values: [
                'GR1-1A',
                'GR1-1B',
                'GR1-2A',
                'GR1-2B',
                'GR1-3A',
                'GR1-3B',
                'GR1-4A',
                'GR1-4B',
                'GR2-1A',
                'GR2-1B',
                'GR2-2A',
                'GR2-2B',
                'GR2-3A',
                'GR2-3B',
                'GR2-4A',
                'GR2-4B',
                'GR3-1A',
                'GR3-1B',
                'GR3-2A',
                'GR3-2B',
                'GR3-3A',
                'GR3-3B',
                'GR3-4A',
                'GR3-4B',
                'GR4-1A',
                'GR4-1B',
                'GR4-2A',
                'GR4-2B',
                'GR4-3A',
                'GR4-3B',
                'GR4-4A',
                'GR4-4B',
                'GR5-1A',
                'GR5-1B',
                'GR5-2A',
                'GR5-2B',
                'GR5-3A',
                'GR5-3B',
                'GR5-4A',
                'GR5-4B',
                'GR6-1A',
                'GR6-1B',
                'GR6-2A',
                'GR6-2B',
                'GR6-3A',
                'GR6-3B',
                'GR6-4A',
                'GR6-4B',
                'maintenance',
                'aux-buffer-1',
                'aux-buffer-2',
                'pre-inspection',
                'inspection',
                'pre-harvest-1',
                'pre-harvest-2',
                'empty-carrier-buffer',
                'laydown-robot',
                'cutagain-robot',
                'pickup-robot',
                'seedling-buffer',
                'cutagain-buffer',
              ],
            },
            rules: {
              string: {
                pattern:
                  '^(GR[123456]-[1-4][AB]|maintenance|aux-buffer-1|aux-buffer-2|pre-inspection|inspection|pre-harvest-1|pre-harvest-2|empty-carrier-buffer|laydown-robot|cutagain-robot|pickup-robot|seedling-buffer|cutagain-buffer)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'rule_10_to',
      options: {
        farmosRpc: {
          isOptional: true,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.LaxCarrierDestination',
    },
  ],
  name: 'Override Routing Table',
};

export const mockExecutionModeActionModel: ProdActions.ActionModel = {
  actionType: 'request',
  description:
    'Sets the execution mode of the default behaviors of the Transfer Conveyance system.  If disabled, no default behaviors will be executed.  If enabled, individual features will be enabled based on the flags in SetTransferConveyanceDefaultBehaviorFeatureFlags',
  fields: [
    {
      displayName: 'Default Behavior Execution Mode',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description:
                "The execution mode that the system/reactors should apply to it's default behaviors.  Currently supports 'on' (EXECUTE_DEFAULT_BEHAVIORS) and 'off' (DO_NOT_EXECUTE_DEFAULT_BEHAVIORS)",
              example: [],
              values: ['EXECUTE_DEFAULT_BEHAVIORS', 'DO_NOT_EXECUTE_DEFAULT_BEHAVIORS'],
            },
            rules: {
              string: {
                pattern: '^(EXECUTE_DEFAULT_BEHAVIORS|DO_NOT_EXECUTE_DEFAULT_BEHAVIORS)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'default_behavior_execution_mode',
      options: {
        farmosRpc: {
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.DefaultBehaviorExecutionMode',
    },
  ],
  name: 'Set Transfer Conveyance Default Behavior Execution Mode',
};

export const mockPreHarvestInspectionRoutingModeActionModel: ProdActions.ActionModel = {
  actionType: 'request',
  description:
    "Specifies the destination lane where the tower should be routed after the pre-harvest inspection. It can only be either 'PRE_HARVEST_LANE_1' or 'PRE_HARVEST_LANE_2'.",
  fields: [
    {
      displayName: 'Mode',
      enumOptions: {
        name: 'RoutingMode',
        reservedName: [],
        reservedRange: [],
        value: [
          {
            name: 'ROUTE_TO_PRE_HARVEST_LANE_1',
            number: 0,
          },
          {
            name: 'ROUTE_TO_PRE_HARVEST_LANE_2',
            number: 1,
          },
        ],
      },
      typeName:
        'plenty.farmos.api.rpc.euphrates.verticalgrow.preharvest.inspection.request.SetPreHarvestInspectionRoutingMode.RoutingMode',
      name: 'mode',
      type: 'TYPE_ENUM',
    },
  ],
  name: 'Set Pre Harvest Inspection Routing Mode',
};

export const mockPreHarvestInspectionFeatureFlagsActionModel: ProdActions.ActionModel = {
  actionType: 'request',
  description: 'Set PreHarvest Default Behavior Feature Flags On/Off to control real-time behavior.',
  fields: [
    {
      displayName: 'Route Tower After Inspection',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'yes or no.',
              example: [],
              values: ['yes', 'no'],
            },
            rules: {
              string: {
                pattern: '^(yes|no)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'route_tower_after_inspection',
      options: {
        farmosRpc: {
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.YesOrNo',
    },
  ],
  name: 'Set Pre Harvest Inspection Default Behavior Feature Flags',
};

export const mockFeatureFlagsActionModel: ProdActions.ActionModel = {
  actionType: 'request',
  description:
    'Enables/disables specific default behavior features.  Ignored unless default behavior execution is enabled via SetTransferConveyanceDefaultBehaviorExecutionMode.',
  fields: [
    {
      displayName: 'Lingering Carriers Management Enabled',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'yes or no.',
              example: [],
              values: ['yes', 'no'],
            },
            rules: {
              string: {
                pattern: '^(yes|no)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'lingering_carriers_management_enabled',
      options: {
        farmosRpc: {
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.YesOrNo',
    },
    {
      displayName: 'Buffer Management Enabled',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'yes or no.',
              example: [],
              values: ['yes', 'no'],
            },
            rules: {
              string: {
                pattern: '^(yes|no)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'buffer_management_enabled',
      options: {
        farmosRpc: {
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.YesOrNo',
    },
    {
      displayName: 'Empty Carriers At Pre Harvest Lanes Management Enabled',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'yes or no.',
              example: [],
              values: ['yes', 'no'],
            },
            rules: {
              string: {
                pattern: '^(yes|no)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'empty_carriers_at_pre_harvest_lanes_management_enabled',
      options: {
        farmosRpc: {
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.YesOrNo',
    },
    {
      displayName: 'Pickup Robot Routing Enabled',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'yes or no.',
              example: [],
              values: ['yes', 'no'],
            },
            rules: {
              string: {
                pattern: '^(yes|no)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'pickup_robot_routing_enabled',
      options: {
        farmosRpc: {
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.YesOrNo',
    },
    {
      displayName: 'Routing Path Override Enabled',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'yes or no.',
              example: [],
              values: ['yes', 'no'],
            },
            rules: {
              string: {
                pattern: '^(yes|no)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'routing_path_override_enabled',
      options: {
        farmosRpc: {
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.YesOrNo',
    },
    {
      displayName: 'Pre Harvest Buffer Flow Routing Enabled',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'yes or no.',
              example: [],
              values: ['yes', 'no'],
            },
            rules: {
              string: {
                pattern: '^(yes|no)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'pre_harvest_buffer_flow_routing_enabled',
      options: {
        farmosRpc: {
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.YesOrNo',
    },
  ],
  name: 'Set Transfer Conveyance Default Behavior Feature Flags',
};

export const mockPauseBufferOutflowActionModel: ProdActions.ActionModel = {
  actionType: 'request',
  description: 'Pauses and unpauses the outflow from a given buffer',
  fields: [
    {
      displayName: 'Pause Buffer Outflow Mode',
      name: 'pause_buffer_outflow_mode',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              values: ['PLAY', 'PLAY_WITH_GOAL_COUNT', 'PAUSE'],
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      options: {
        farmosRpc: {
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.PlayBufferOutflowMode',
    },
    {
      displayName: 'Goal Count',
      name: 'goal_count',
      options: {
        farmosRpc: {
          description: 'The number of carriers to be allowed into a buffer',
          example: ['1', '13', '29'],
          isOptional: true,
          values: [],
        },
        rules: {
          int32: {
            gt: 0,
          },
        },
      },
      type: 'TYPE_INT32',
    },
    {
      displayName: 'Buffer',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              values: [
                'AUX_BUFFER_1',
                'AUX_BUFFER_2',
                'PH_CARRIER_BUFFER',
                'SEEDLING_BUFFER',
                'CUTAGAIN_BUFFER',
                'CUTBOT_BUFFER',
                'PICKUP_BUFFER',
              ],
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'buffer',
      options: {
        farmosRpc: {
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.Lax1TransferConveyanceBuffer',
    },
  ],
  name: 'Pause Buffer Outflow',
};

export const mockMoveCarrierActionModel: ProdActions.ActionModel = {
  actionType: 'request',
  description:
    'Move the specified Carrier from the (optional) initial CarrierDestination to a different CarrierDestination.',
  fields: [
    {
      displayName: 'Carrier',
      name: 'carrier_id',
      options: {
        farmosRpc: {
          description: 'ID of the carrier that should be moved',
          example: ['1', '13', '69'],
          values: [],
        },
        rules: {
          int32: {
            gt: 0,
          },
        },
      },
      type: 'TYPE_INT32',
    },
    {
      displayName: 'To Location',
      fields: [
        {
          displayName: 'Value',
          name: 'value',
          options: {
            farmosRpc: {
              description: 'The ID of Destination from which the Tower should be moved.',
              example: [],
              values: [
                'GR1-1A',
                'GR1-1B',
                'GR1-2A',
                'GR1-2B',
                'GR1-3A',
                'GR1-3B',
                'GR1-4A',
                'GR1-4B',
                'GR2-1A',
                'GR2-1B',
                'GR2-2A',
                'GR2-2B',
                'GR2-3A',
                'GR2-3B',
                'GR2-4A',
                'GR2-4B',
                'GR3-1A',
                'GR3-1B',
                'GR3-2A',
                'GR3-2B',
                'GR3-3A',
                'GR3-3B',
                'GR3-4A',
                'GR3-4B',
                'GR4-1A',
                'GR4-1B',
                'GR4-2A',
                'GR4-2B',
                'GR4-3A',
                'GR4-3B',
                'GR4-4A',
                'GR4-4B',
                'GR5-1A',
                'GR5-1B',
                'GR5-2A',
                'GR5-2B',
                'GR5-3A',
                'GR5-3B',
                'GR5-4A',
                'GR5-4B',
                'GR6-1A',
                'GR6-1B',
                'GR6-2A',
                'GR6-2B',
                'GR6-3A',
                'GR6-3B',
                'GR6-4A',
                'GR6-4B',
                'maintenance',
                'aux-buffer-1',
                'aux-buffer-2',
                'pre-inspection',
                'inspection',
                'pre-harvest-1',
                'pre-harvest-2',
                'empty-carrier-buffer',
                'laydown-robot',
                'cutagain-robot',
                'pickup-robot',
                'seedling-buffer',
                'cutagain-buffer',
              ],
            },
            rules: {
              string: {
                pattern:
                  '^(GR[123456]-[1-4][AB]|maintenance|aux-buffer-1|aux-buffer-2|pre-inspection|inspection|pre-harvest-1|pre-harvest-2|empty-carrier-buffer|laydown-robot|cutagain-robot|pickup-robot|seedling-buffer|cutagain-buffer)$',
              },
            },
          },
          type: 'TYPE_STRING',
        },
      ],
      name: 'to_location',
      options: {
        farmosRpc: {
          isOptional: false,
          values: [],
        },
      },
      repeated: false,
      type: 'TYPE_MESSAGE',
      typeName: 'plenty.farmos.api.rpc.LaxCarrierDestination',
    },
  ],
  name: 'Move Carrier',
};
