import {
  Aggregation,
  DerivedObservationDefinition,
  Output,
  WindowDuration,
} from '@plentyag/core/src/types/derived-observations';

export const mockDerivedObservationDefinitions: DerivedObservationDefinition[] = [
  {
    type: 'DerivedObservationDefinition',
    id: 'effd6e1c-b299-4dcf-aead-67fe53a964cc',
    createdAt: '2022-03-04T20:38:59.954043Z',
    updatedAt: '2022-03-04T20:38:59.954043Z',
    createdBy: 'gdebeaupuis',
    updatedBy: 'gdebeaupuis',
    streamName: 'derivedName0',
    observationKey: {
      path: 'sites/SSF2',
      observationName: 'AirTemperatureMeanOneMinutePlus5',
    },
    window: WindowDuration.oneMinute,
    output: Output.double,
    sourceStreamNames: ['name0'],
    expression: 'name0 + 5',
    outputMeasurementType: 'TEMPERATURE',
    outputMeasurementTypeUnits: 'C',
    dependents: [
      {
        type: 'DerivedObservationDefinition',
        id: '2f48160b-9308-4da8-ad9e-d69831a6ff39',
        createdAt: '2022-03-04T20:44:26.773204Z',
        updatedAt: '2022-03-04T20:44:26.773204Z',
        createdBy: 'gdebeaupuis',
        updatedBy: 'gdebeaupuis',
        streamName: 'derivedName1',
        observationKey: {
          path: 'sites/SSF2',
          observationName: 'AirTemperatureMeanOneMinutePlus5Times5',
        },
        window: WindowDuration.oneMinute,
        output: Output.double,
        sourceStreamNames: ['derivedName0'],
        expression: 'derivedName0 * 5',
        outputMeasurementType: 'TEMPERATURE',
        outputMeasurementTypeUnits: 'C',
        dependents: [],
        dependencies: [],
      },
    ],
    dependencies: [
      {
        type: 'BaseObservationDefinition',
        id: '8e359b2b-bfee-493b-8671-a0109eaa229e',
        createdAt: '2022-03-04T20:33:43.733403Z',
        updatedAt: '2022-03-04T20:33:43.733403Z',
        createdBy: 'gdebeaupuis',
        updatedBy: 'gdebeaupuis',
        streamName: 'name0',
        observationKey: {
          path: 'sites/SSF2',
          observationName: 'AirTemperature',
        },
        window: WindowDuration.oneMinute,
        output: Output.double,
        aggregation: Aggregation.mean,
        comment: '',
        dependents: [],
      },
    ],
  },
  {
    type: 'DerivedObservationDefinition',
    id: 'fff00856-0a80-43bd-b141-f053cf712e44',
    createdAt: '2022-02-28T16:02:16.465489Z',
    updatedAt: '2022-02-28T16:02:16.465502Z',
    createdBy: 'nasi',
    updatedBy: 'nasi',
    streamName: 'LAR1NorthBuildingGP19SupplyOutletPressureAvg5MinDerived',
    observationKey: {
      path: 'sites/LAR1/areas/NorthBuilding/lines/GP19',
      observationName: 'SupplyOutletPressure',
    },
    window: WindowDuration.fiveMinutes,
    output: Output.double,
    sourceStreamNames: ['LAR1NorthBuildingGP19SupplyOutletPressureAvg5Min'],
    expression: 'LAR1NorthBuildingGP19SupplyOutletPressureAvg5Min',
    outputMeasurementType: 'PRESSURE',
    outputMeasurementTypeUnits: 'PSI',
    dependents: [],
    dependencies: [],
  },
];
