export const mockGenealogyData: ProdResources.FocusedResource = {
  numberOfNewerOperationsNotShown: 0,
  newestOperationNotShown: null,
  numberOfOlderOperationsNotShown: 0,
  oldestOperationNotShown: null,
  alive: false,
  operations: [
    {
      antecedents: [
        {
          hasAntecedents: false,
          numberOfNewerOperationsNotShown: 0,
          newestOperationNotShown: null,
          numberOfOlderOperationsNotShown: 0,
          oldestOperationNotShown: null,
          alive: false,
          materialId: '310-0000015A:20-050-09-33-44:525900-02-01',
          operations: [
            {
              id: '123',
              startDt: '2020-11-28T17:01:51.985Z',
              endDt: '2020-11-28T17:01:51.985Z',
              machine: {
                areaName: 'Seeding',
                farmdefMachineId: '',
                lineName: 'TraySeeding',
                siteName: 'SSF2',
                traceabilityMachineId: 'ec6fc31a-b72c-42b5-927b-8232dc929cd6',
              },
              stateIn: null,
              stateOut: null,
              type: 'Cult Seed Tray',
              username: 'lneir',
              materialsConsumed: [],
              materialsCreated: [],
            },
            {
              id: '123',
              startDt: '2020-11-30T17:01:51.985Z',
              endDt: '2020-11-30T17:01:51.985Z',
              machine: {
                areaName: 'Seeding',
                farmdefMachineId: '',
                lineName: 'TraySeeding',
                siteName: 'SSF2',
                traceabilityMachineId: 'ec6fc31a-b72c-42b5-927b-8232dc929cd6',
              },
              stateIn: null,
              stateOut: null,
              type: 'Cult Seed Tray',
              username: 'lneir',
              materialsConsumed: [],
              materialsCreated: [],
            },
          ],
          parent: null,
        },
        {
          numberOfNewerOperationsNotShown: 0,
          newestOperationNotShown: null,
          numberOfOlderOperationsNotShown: 0,
          oldestOperationNotShown: null,
          alive: false,
          hasAntecedents: false,
          materialId: '320-0000008A:20-232-08-45-19:PO7400',
          operations: [
            {
              id: '123',
              startDt: '2020-11-28T17:01:51.985Z',
              endDt: '2020-11-28T17:01:51.985Z',
              machine: {
                areaName: 'Seeding',
                farmdefMachineId: '',
                lineName: 'TraySeeding',
                siteName: 'SSF2',
                traceabilityMachineId: 'ec6fc31a-b72c-42b5-927b-8232dc929cd6',
              },
              stateIn: null,
              stateOut: null,
              type: 'Cult Seed Tray',
              username: 'lneir',
              materialsConsumed: [],
              materialsCreated: [],
            },
            {
              id: '123',
              startDt: '2020-11-30T17:01:51.985Z',
              endDt: '2020-11-30T17:01:51.985Z',
              machine: {
                areaName: 'Seeding',
                farmdefMachineId: '',
                lineName: 'TraySeeding',
                siteName: 'SSF2',
                traceabilityMachineId: 'ec6fc31a-b72c-42b5-927b-8232dc929cd6',
              },
              stateIn: null,
              stateOut: null,
              type: 'Cult Seed Tray',
              username: 'lneir',
              materialsConsumed: [],
              materialsCreated: [],
            },
          ],
          parent: null,
        },
      ],
      id: '123',
      startDt: '2020-11-30T17:01:51.985Z',
      endDt: '2020-11-30T17:01:51.985Z',
      machine: {
        areaName: 'Seeding',
        farmdefMachineId: '',
        lineName: 'TraySeeding',
        siteName: 'SSF2',
        traceabilityMachineId: 'ec6fc31a-b72c-42b5-927b-8232dc929cd6',
      },
      stateIn: null,
      stateOut: null,
      subsequents: [],
      type: 'Cult Seed Tray',
      username: 'lneir',
      materialsConsumed: [],
      materialsCreated: [],
    },
    {
      id: '123',
      antecedents: [],
      startDt: '2020-12-01T17:01:51.985Z',
      endDt: '2020-12-01T17:01:51.985Z',
      machine: {
        areaName: 'Germination',
        farmdefMachineId: '',
        lineName: 'TableGermination',
        siteName: 'SSF2',
        traceabilityMachineId: 'ec6fc31a-b72c-42b5-927b-8232dc929cd6',
      },
      stateIn: {
        isLatest: false,
        updatedAt: '2021-05-18T14:05:50.200Z',
        childResourceStateIds: [],
        containerId: 'container-xyz',
        containerLabels: [],
        containerObj: {
          createdAt: '2021-05-12T12:19:59.138Z',
          containerType: 'TRAY',
          id: 'xyz',
          serial: 'serial-xyz',
          properties: {},
        },
        containerStatus: 'IN_USE',
        id: 'xyz',
        location: {
          machine: {
            areaName: 'Germination',
            farmdefMachineId: '',
            lineName: 'TableGermination',
            siteName: 'SSF2',
            traceabilityMachineId: 'ec6fc31a-b72c-42b5-927b-8232dc929cd6',
          },
        },
        materialId: 'xyz',
        materialLabels: [],
        materialObj: {
          id: 'xyz',
          lotName: 'lot-xyz',
          materialType: 'LOADED_TRAY',
          product: 'WHC',
          properties: {},
        },
        materialStatus: 'IN_USE',
        parentResourceStateId: null,
      },
      stateOut: {
        isLatest: false,
        updatedAt: '2021-05-18T14:05:50.200Z',
        childResourceStateIds: [],
        containerId: 'container-xyz',
        containerLabels: [],
        containerObj: {
          createdAt: '2021-05-12T12:19:59.138Z',
          containerType: 'TRAY',
          id: 'xyz',
          serial: 'serial-xyz',
          properties: {},
        },
        containerStatus: 'IN_USE',
        id: 'xyz',
        location: {
          machine: {
            areaName: 'Germination',
            farmdefMachineId: '',
            lineName: 'TableGermination',
            siteName: 'SSF2',
            traceabilityMachineId: 'ec6fc31a-b72c-42b5-927b-8232dc929cd6',
          },
        },
        materialId: 'xyz',
        materialLabels: ['Sensor Tray'],
        materialObj: {
          id: 'xyz',
          lotName: 'lot-xyz',
          materialType: 'LOADED_TRAY',
          product: 'WHC',
          properties: {},
        },
        materialStatus: 'IN_USE',
        parentResourceStateId: null,
      },
      subsequents: [],
      type: 'Add Label',
      username: 'lneir',
      materialsConsumed: [],
      materialsCreated: [],
    },
    {
      id: '123',
      antecedents: [],
      startDt: '2020-12-03T17:01:51.985Z',
      endDt: '2020-12-03T17:01:51.985Z',
      machine: {
        areaName: 'Germination',
        farmdefMachineId: '',
        lineName: 'TableGermination',
        siteName: 'SSF2',
        traceabilityMachineId: 'ec6fc31a-b72c-42b5-927b-8232dc929cd6',
      },
      stateIn: {
        isLatest: false,
        updatedAt: '2021-05-18T14:05:50.200Z',
        childResourceStateIds: [],
        containerId: 'container-xyz',
        containerLabels: [],
        containerObj: {
          createdAt: '2021-05-12T12:19:59.138Z',
          containerType: 'TRAY',
          id: 'xyz',
          serial: 'serial-xyz',
          properties: {},
        },
        containerStatus: 'IN_USE',
        id: 'xyz',
        location: {
          machine: {
            areaName: 'Germination',
            farmdefMachineId: '',
            lineName: 'TableGermination',
            siteName: 'SSF2',
            traceabilityMachineId: 'ec6fc31a-b72c-42b5-927b-8232dc929cd6',
          },
        },
        materialId: 'xyz',
        materialLabels: [],
        materialObj: {
          id: 'xyz',
          lotName: 'lot-xyz',
          materialType: 'LOADED_TRAY',
          product: 'WHC',
          properties: {},
        },
        materialStatus: 'IN_USE',
        parentResourceStateId: null,
      },
      stateOut: {
        isLatest: false,
        updatedAt: '2021-05-18T14:05:50.200Z',
        childResourceStateIds: [],
        containerId: 'container-xyz',
        containerLabels: [],
        containerObj: {
          createdAt: '2021-05-12T12:19:59.138Z',
          containerType: 'TRAY',
          id: 'xyz',
          serial: 'serial-xyz',
          properties: {},
        },
        containerStatus: 'IN_USE',
        id: 'xyz',
        location: {
          machine: {
            areaName: 'Germination',
            farmdefMachineId: '',
            lineName: 'TableGermination',
            siteName: 'SSF2',
            traceabilityMachineId: 'ec6fc31a-b72c-42b5-927b-8232dc929cd6',
          },
        },
        materialId: 'xyz',
        materialLabels: ['Sensor Tray'],
        materialObj: {
          id: 'xyz',
          lotName: 'lot-xyz',
          materialType: 'LOADED_TRAY',
          product: 'WHC',
          properties: {},
        },
        materialStatus: 'IN_USE',
        parentResourceStateId: null,
      },
      subsequents: [],
      type: 'Add Label',
      username: 'lneir',
      materialsConsumed: [],
      materialsCreated: [],
    },
    {
      id: '123',
      antecedents: [],
      startDt: '2020-12-10T17:01:51.985Z',
      endDt: '2020-12-10T17:01:51.985Z',
      machine: {
        areaName: 'CentralProcessing',
        farmdefMachineId: '',
        lineName: 'TowerProcessing',
        siteName: 'SSF2',
        traceabilityMachineId: 'd9ae66eb-0b9e-48c7-b8a8-66b6b742360a',
      },
      stateIn: null,
      stateOut: null,
      subsequents: [
        {
          numberOfNewerOperationsNotShown: 0,
          newestOperationNotShown: null,
          numberOfOlderOperationsNotShown: 0,
          oldestOperationNotShown: null,
          alive: false,
          hasSubsequents: true,
          materialId: 'tower1-xyz',
          operations: [
            {
              id: '123',
              startDt: '2020-12-10T17:01:51.985Z',
              endDt: '2020-12-10T17:01:51.985Z',
              machine: {
                areaName: 'CentralProcessing',
                farmdefMachineId: '',
                lineName: 'TowerProcessing',
                siteName: 'SSF2',
                traceabilityMachineId: 'd9ae66eb-0b9e-48c7-b8a8-66b6b742360a',
              },
              stateIn: null,
              stateOut: null,
              type: 'CProc Transplant Tower',
              username: 'lneir',
              materialsConsumed: [],
              materialsCreated: [],
            },
            {
              id: '123',
              startDt: '2020-12-10T17:04:51.985Z',
              endDt: '2020-12-10T17:04:51.985Z',
              machine: {
                areaName: 'VerticalGrow',
                farmdefMachineId: '',
                lineName: 'GrowRoom',
                siteName: 'SSF2',
                traceabilityMachineId: 'd9ae66eb-0b9e-48c7-b8a8-66b6b742360a',
              },
              stateIn: null,
              stateOut: null,
              type: 'Load Grow Line',
              username: 'lneir',
              materialsConsumed: [],
              materialsCreated: [],
            },
            {
              id: '123',
              startDt: '2020-12-14T17:00:00.000Z',
              endDt: '2020-12-14T17:00:00.000Z',
              machine: {
                areaName: 'VerticalGrow',
                farmdefMachineId: '',
                lineName: 'GrowRoom',
                siteName: 'SSF2',
                traceabilityMachineId: 'd9ae66eb-0b9e-48c7-b8a8-66b6b742360a',
              },
              stateIn: null,
              stateOut: null,
              type: 'Index',
              username: 'lneir',
              materialsConsumed: [],
              materialsCreated: [],
            },
          ],
          parent: null,
        },
      ],
      type: 'CProc Transplant Tower',
      username: 'lneir',
      materialsConsumed: [],
      materialsCreated: [],
    },
    {
      id: '123',
      antecedents: [],
      startDt: '2020-12-10T17:01:55.000Z',
      endDt: '2020-12-10T17:01:55.000Z',
      machine: {
        areaName: 'CentralProcessing',
        farmdefMachineId: '',
        lineName: 'TowerProcessing',
        siteName: 'SSF2',
        traceabilityMachineId: 'd9ae66eb-0b9e-48c7-b8a8-66b6b742360a',
      },
      stateIn: null,
      stateOut: null,
      subsequents: [
        {
          numberOfNewerOperationsNotShown: 0,
          newestOperationNotShown: null,
          numberOfOlderOperationsNotShown: 0,
          oldestOperationNotShown: null,
          alive: false,
          hasSubsequents: true,
          materialId: 'tower2-xyz',
          operations: [
            {
              id: '123',
              startDt: '2020-12-10T17:01:55.000Z',
              endDt: '2020-12-10T17:01:55.000Z',
              machine: {
                areaName: 'CentralProcessing',
                farmdefMachineId: '',
                lineName: 'TowerProcessing',
                siteName: 'SSF2',
                traceabilityMachineId: 'd9ae66eb-0b9e-48c7-b8a8-66b6b742360a',
              },
              stateIn: null,
              stateOut: null,
              type: 'CProc Transplant Tower',
              username: 'lneir',
              materialsConsumed: [],
              materialsCreated: [],
            },
            {
              id: '123',
              startDt: '2020-12-10T17:01:57.000Z',
              endDt: '2020-12-10T17:01:57.000Z',
              machine: {
                areaName: 'VerticalGrow',
                farmdefMachineId: '',
                lineName: 'GrowRoom',
                siteName: 'SSF2',
                traceabilityMachineId: 'd9ae66eb-0b9e-48c7-b8a8-66b6b742360a',
              },
              stateIn: null,
              stateOut: null,
              type: 'Load Grow Line',
              username: 'lneir',
              materialsConsumed: [],
              materialsCreated: [],
            },
            {
              id: '123',
              startDt: '2020-12-12T17:01:57.000Z',
              endDt: '2020-12-12T17:01:57.000Z',
              machine: {
                areaName: 'VerticalGrow',
                farmdefMachineId: '',
                lineName: 'GrowRoom',
                siteName: 'SSF2',
                traceabilityMachineId: 'd9ae66eb-0b9e-48c7-b8a8-66b6b742360a',
              },
              stateIn: null,
              stateOut: null,
              type: 'Index',
              username: 'lneir',
              materialsConsumed: [],
              materialsCreated: [],
            },
            {
              id: '123',
              startDt: '2020-12-13T17:01:57.000Z',
              endDt: '2020-12-13T17:01:57.000Z',
              machine: {
                areaName: 'VerticalGrow',
                farmdefMachineId: '',
                lineName: 'GrowRoom',
                siteName: 'SSF2',
                traceabilityMachineId: 'd9ae66eb-0b9e-48c7-b8a8-66b6b742360a',
              },
              stateIn: null,
              stateOut: null,
              type: 'Index',
              username: 'lneir',
              materialsConsumed: [],
              materialsCreated: [],
            },
          ],
          parent: null,
        },
      ],
      type: 'CProc Transplant Tower',
      username: 'lneir',
      materialsConsumed: [],
      materialsCreated: [],
    },
  ],
  parent: null,
};
