import { CropWithFarmInfo } from '../types';

export const mockCrops: CropWithFarmInfo[] = [
  {
    childCrops: [],
    cropTypeName: 'LeafyGreens',
    description: null,
    displayAbbreviation: 'BRN',
    displayName: 'Mini Head Romaine - Breen',
    hasFarm: {
      'sites/LAX1/farms/LAX1': false,
      'sites/SSF2/farms/Tigris': true,
    },
    skus: [],
    isSeedable: true,
    name: 'BRN',
    commonName: 'Breen',
    path: 'crops/BRN',
    media: 'COIR',
    cultivar: 'Mini Head Romaine',
    properties: {
      recipes: {
        tigris: {
          harvesterSettings: {
            washSpeed: {
              units: 'mm/s',
              value: 280,
              maxValue: 300,
              minValue: 150,
            },
            toteWeight: {
              units: 'g',
              value: 1750,
              maxValue: 1750,
              minValue: 150,
            },
            harvestDepth: {
              units: 'mm',
              value: 20,
              maxValue: 135,
              minValue: 5,
            },
            harvestSpeed: {
              units: 'mm/s',
              value: 450,
              maxValue: 450,
              minValue: 0,
            },
            breakawaySpeed: {
              units: 'mm/s',
              value: 450,
              maxValue: 450,
              minValue: 150,
            },
          },
          propIrrigationSchedule: {
            '1': 300,
            '3': 300,
            '5': 300,
            '7': 300,
            '9': 300,
            '11': 300,
            '12': 300,
            '13': 300,
            '14': 300,
            '15': 300,
            '16': 300,
            '17': 300,
            '18': 300,
          },
          propIrrigationMinVolume: 300,
        },
      },
    },
    seedPartNumbers: [],
  },
  {
    childCrops: [
      {
        defaultCropName: 'JCC',
        allowedCropNames: ['JCC'],
        minRatio: 0.6,
        maxRatio: 0.7,
        targetRatio: 0.65,
      },
      {
        defaultCropName: 'MZC',
        allowedCropNames: ['MZC'],
        minRatio: 0.3,
        maxRatio: 0.4,
        targetRatio: 0.35,
      },
    ],
    cropTypeName: 'LeafyGreens',
    description: null,
    displayAbbreviation: 'YCH',
    displayName: 'Yellow Chard - Oriole',
    hasFarm: {
      'sites/LAX1/farms/LAX1': false,
      'sites/SSF2/farms/Tigris': true,
    },
    skus: [],
    isSeedable: true,
    name: 'YCH',
    commonName: 'Chard',
    path: 'crops/YCH',
    media: 'COIR',
    cultivar: 'Oriole',
    properties: {},
    seedPartNumbers: [],
  },
  {
    childCrops: [],
    cropTypeName: 'LeafyGreens',
    description: null,
    displayAbbreviation: 'BRN:COMPOUND_1',
    displayName: 'Mini Head Romaine - Breen',
    hasFarm: {
      'sites/LAX1/farms/LAX1': false,
      'sites/SSF2/farms/Tigris': true,
    },
    skus: [],
    isSeedable: true,
    name: 'BRN:COMPOUND_1',
    commonName: 'Romaine',
    path: 'crops/BRN:COMPOUND_1',
    media: 'COIR',
    cultivar: 'Mini Head Romaine',
    properties: {},
    seedPartNumbers: [],
  },
];
