import { SkuWithFarmInfo } from '../types';

export const mockSkus: SkuWithFarmInfo[] = [
  {
    allowedCropNames: ['B11'],
    childSkuName: null,
    packagingLotCropCode: 'B11',
    defaultCropName: 'B11',
    description: null,
    displayAbbreviation: 'WHR Clam',
    displayName: 'Baby Kale Clamshell',
    externalExpirationDays: 5,
    gtin: '00810567030521',
    hasFarm: {
      'sites/LAX1/farms/LAX1': false,
      'sites/LAR1/farms/Laramie': false,
      'sites/SSF2/farms/Sierra': false,
      'sites/SSF2/farms/Taurus': false,
      'sites/SSF2/farms/Tigris': true,
    },
    internalExpirationDays: 12,
    kind: 'sku',
    labelPrimaryColor: 'red',
    labelSecondaryColor: 'blue',
    name: 'KaleClam4oz',
    netsuiteItem: '5-004-0002-03',
    packageImagery: '/static/img/packaging/skus/B11.jpg',
    path: 'skus/KaleClam4oz',
    productName: 'Baby Kale',
    properties: {
      test: 'some-value',
    },
    skuTypeName: 'Clamshell4oz',
    brandTypeName: 'Plenty',
    productWeightOz: 4,
  },
  {
    allowedCropNames: ['B11', 'WHC'],
    childSkuName: 'None',
    packagingLotCropCode: 'WHC',
    defaultCropName: 'WHC',
    description: ' ',
    displayAbbreviation: 'B11-Clam4.5oz',
    displayName: 'Baby Kale Clamshell 4.5oz',
    externalExpirationDays: 10,
    gtin: '00810567030415',
    hasFarm: {
      'sites/LAX1/farms/LAX1': false,
      'sites/LAR1/farms/Laramie': false,
      'sites/SSF2/farms/Sierra': false,
      'sites/SSF2/farms/Taurus': false,
      'sites/SSF2/farms/Tigris': true,
    },
    internalExpirationDays: 4,
    kind: 'sku',
    labelPrimaryColor: '#542E8E',
    labelSecondaryColor: '#FED141',
    name: 'B11Clamshell4o5oz',
    netsuiteItem: '5-004-0001-04',
    packageImagery: '/static/img/packaging/skus/B11.jpg',
    path: 'skus/B11Clamshell4o5oz',
    productName: 'Baby Kale',
    properties: {},
    skuTypeName: 'Clamshell4o5oz',
    brandTypeName: 'Plenty',
    productWeightOz: 4,
  },
  {
    displayAbbreviation: 'C11Bulk3lb',
    displayName: 'Sweet Sunrise Bulk 3lb',
    path: 'skus/C11Bulk3lb',
    name: 'C11Bulk3lb',
    kind: 'sku',
    description: null,
    netsuiteItem: '5-003-0003-02',
    gtin: '90810567030562',
    packageImagery: undefined,
    hasFarm: {
      'sites/LAX1/farms/LAX1': false,
      'sites/LAR1/farms/Laramie': false,
      'sites/SSF2/farms/Sierra': false,
      'sites/SSF2/farms/Taurus': false,
      'sites/SSF2/farms/Tigris': true,
    },
    productName: 'Sweet Sunrise',
    skuTypeName: 'Bulk3lb',
    defaultCropName: 'C11',
    packagingLotCropCode: 'C11',
    allowedCropNames: ['C11'],
    labelPrimaryColor: '',
    labelSecondaryColor: '',
    internalExpirationDays: 5,
    externalExpirationDays: 14,
    childSkuName: null,
    properties: {},
  },
  {
    displayAbbreviation: 'B20Case6Clamshell4oz',
    displayName: 'TEST_BABY 6ct Case of Clamshells 4.0oz',
    path: 'skus/B20Case6Clamshell4oz',
    name: 'B20Case6Clamshell4oz',
    kind: 'sku',
    description: 'Test Baby Arugula',
    netsuiteItem: '5-005-0002-01',
    gtin: '90810567030593',
    packageImagery: undefined,
    hasFarm: {
      'sites/LAX1/farms/LAX1': false,
      'sites/LAR1/farms/Laramie': false,
      'sites/SSF2/farms/Sierra': false,
      'sites/SSF2/farms/Taurus': false,
      'sites/SSF2/farms/Tigris': true,
    },
    productName: 'TEST_BABY',
    skuTypeName: 'Case6Clamshell4oz',
    defaultCropName: null,
    packagingLotCropCode: 'B20',
    allowedCropNames: ['BAC', 'B20'],
    labelPrimaryColor: '',
    labelSecondaryColor: '',
    internalExpirationDays: 4,
    externalExpirationDays: 11,
    childSkuName: null,
    properties: {},
  },
];
