import { PackagingLotTestStatus } from '@plentyag/core/src/types';

import { FinishedGoodsObj, SkuObj } from '../hooks';
import { FinishedGoodsStatus } from '../types';

export const mockFinishedGoodsDataLots: FinishedGoodsObj[] = [
  {
    nodeId: '0c914f7e-4cbe-4a80-96e3-cfde8048e4d0',
    lot: {
      createdAt: '2022-09-02T00:08:11.773Z',
      id: '0c914f7e-4cbe-4a80-96e3-cfde8048e4d0',
      lotName: '5-LAX1-C11-245',
      materialType: 'PACKAGING_LOT',
      product: 'C11',
      properties: {
        farmName: 'LAX1',
        overriddenLtAuthor: 'otapia',
        overriddenLtNotes:
          'Testing a more long string in the notes section to see how is the behavior in the UI in toggle view',
        overriddenLtStatus: PackagingLotTestStatus.FAIL,
        overriddenLtUpdatedAt: '2022-09-02T13:12:37.587Z',
        overriddenQaAuthor: 'otapia',
        overriddenQaNotes:
          'Testing a more long string in the notes section to see how is the behavior in the UI in toggle view',
        overriddenQaStatus: PackagingLotTestStatus.HOLD,
        overriddenQaUpdatedAt: '2022-09-02T13:12:23.751Z',
        packDate: '2022-09-02',
        packageComponents: {
          empty: true,
          traversableAgain: true,
        },
        passedLtStatus: PackagingLotTestStatus.NONE,
        passedQaStatus: PackagingLotTestStatus.NONE,
        releasedAt: null,
        siteName: 'LAX1',
      },
      updatedAt: '2022-09-02T13:12:36.333Z',
    },
    skus: [
      {
        sku: {
          allowedCropNames: ['C11'],
          childSkuName: 'C11Clamshell4o5oz',
          defaultCropName: 'C11',
          description: null,
          displayAbbreviation: 'C11Case6Clamshell4o5oz',
          displayName: 'Sweet Sunrise 6ct Case of Clamshells 4.5oz',
          externalExpirationDays: 10,
          gtin: '10810567030429',
          internalExpirationDays: 4,
          kind: 'sku',
          labelPrimaryColor: '#FED141',
          labelSecondaryColor: '#D50032',
          name: 'C11Case6Clamshell4o5oz',
          netsuiteItem: '5-003-0004-06',
          packagingLotCropCode: 'C11',
          path: 'skus/C11Case6Clamshell4o5oz',
          productName: 'Sweet Sunrise',
          properties: {},
          skuTypeName: 'Case6Clamshell4o5oz',
        },
        count: 1,
      },
    ],
    crop: {
      childCrops: [
        {
          allowedCropNames: ['CRC'],
          defaultCropName: 'CRC',
          maxRatio: 1,
          minRatio: 0,
          targetRatio: null,
        },
        {
          allowedCropNames: ['GFF:NPI'],
          defaultCropName: 'GFF:NPI',
          maxRatio: 1,
          minRatio: 0,
          targetRatio: null,
        },
        {
          allowedCropNames: ['GRC'],
          defaultCropName: 'GRC',
          maxRatio: 1,
          minRatio: 0,
          targetRatio: null,
        },
        {
          allowedCropNames: ['BBB:NPI'],
          defaultCropName: 'BBB:NPI',
          maxRatio: 1,
          minRatio: 0,
          targetRatio: null,
        },
      ],
      commonName: 'Unbeetable Blend (AKA Sweet Sunrise)',
      cropTypeName: 'LeafyGreens',
      cultivar: null,
      description: null,
      displayAbbreviation: 'C11',
      displayName: 'Unbeetable Blend (AKA Sweet Sunrise) - C11',
      isSeedable: false,
      media: '',
      name: 'C11',
      path: 'crops/C11',
      properties: {
        plannedGrowDays: 12,
      },
      seedPartNumbers: [],
    },
    expDate: new Date(new Date('2022-09-06T07:00:00.000Z')),
    status: FinishedGoodsStatus.EXPIRED,
    releaseDetails: {
      overriddenLtAuthor: 'otapia',
      overriddenLtNotes:
        'Testing a more long string in the notes section to see how is the behavior in the UI in toggle view',
      overriddenLtStatus: PackagingLotTestStatus.FAIL,
      overriddenLtUpdatedAt: '2022-09-02T13:12:37.587Z',
      overriddenQaAuthor: 'otapia',
      overriddenQaNotes:
        'Testing a more long string in the notes section to see how is the behavior in the UI in toggle view',
      overriddenQaStatus: PackagingLotTestStatus.HOLD,
      overriddenQaUpdatedAt: '2022-09-02T13:12:23.751Z',
      passedLtStatus: PackagingLotTestStatus.NONE,
      passedQaStatus: PackagingLotTestStatus.NONE,
      releasedAt: null,
    },
  },
  {
    nodeId: '54688a82-1a2e-4750-ad09-e7205896e110',
    lot: {
      createdAt: '2022-08-07T00:00:20.052Z',
      id: '54688a82-1a2e-4750-ad09-e7205896e110',
      lotName: '5-LAX1-C11-219',
      materialType: 'PACKAGING_LOT',
      product: 'C11',
      properties: {
        farmName: 'LAX1',
        overriddenLtStatus: PackagingLotTestStatus.NONE,
        overriddenQaStatus: PackagingLotTestStatus.NONE,
        packDate: '2022-08-07',
        passedLtStatus: PackagingLotTestStatus.NONE,
        passedQaStatus: PackagingLotTestStatus.NONE,
        releasedAt: null,
        siteName: 'LAX1',
      },
      updatedAt: '2022-08-07T01:46:06.262Z',
    },
    skus: [
      {
        sku: {
          allowedCropNames: ['C11'],
          childSkuName: 'C11Clamshell4o5oz',
          defaultCropName: 'C11',
          description: null,
          displayAbbreviation: 'C11Case6Clamshell4o5oz',
          displayName: 'Sweet Sunrise 6ct Case of Clamshells 4.5oz',
          externalExpirationDays: 10,
          gtin: '10810567030429',
          internalExpirationDays: 4,
          kind: 'sku',
          labelPrimaryColor: '#FED141',
          labelSecondaryColor: '#D50032',
          name: 'C11Case6Clamshell4o5oz',
          netsuiteItem: '5-003-0004-06',
          packagingLotCropCode: 'C11',
          path: 'skus/C11Case6Clamshell4o5oz',
          productName: 'Sweet Sunrise',
          properties: {},
          skuTypeName: 'Case6Clamshell4o5oz',
        },
        count: 1,
      },
    ],
    crop: {
      childCrops: [
        {
          allowedCropNames: ['CRC'],
          defaultCropName: 'CRC',
          maxRatio: 1,
          minRatio: 0,
          targetRatio: null,
        },
        {
          allowedCropNames: ['GFF:NPI'],
          defaultCropName: 'GFF:NPI',
          maxRatio: 1,
          minRatio: 0,
          targetRatio: null,
        },
        {
          allowedCropNames: ['GRC'],
          defaultCropName: 'GRC',
          maxRatio: 1,
          minRatio: 0,
          targetRatio: null,
        },
        {
          allowedCropNames: ['BBB:NPI'],
          defaultCropName: 'BBB:NPI',
          maxRatio: 1,
          minRatio: 0,
          targetRatio: null,
        },
      ],
      commonName: 'Unbeetable Blend (AKA Sweet Sunrise)',
      cropTypeName: 'LeafyGreens',
      cultivar: null,
      description: null,
      displayAbbreviation: 'C11',
      displayName: 'Unbeetable Blend (AKA Sweet Sunrise) - C11',
      isSeedable: false,
      media: '',
      name: 'C11',
      path: 'crops/C11',
      properties: {
        plannedGrowDays: 12,
      },
      seedPartNumbers: [],
    },
    expDate: new Date(new Date('2022-08-11T07:00:00.000Z')),
    status: FinishedGoodsStatus.EXPIRED,
    releaseDetails: {
      overriddenLtStatus: PackagingLotTestStatus.NONE,
      overriddenQaStatus: PackagingLotTestStatus.NONE,
      passedLtStatus: PackagingLotTestStatus.NONE,
      passedQaStatus: PackagingLotTestStatus.NONE,
      releasedAt: null,
    },
  },
];

export const mockFinishedGoodsDataSkus: SkuObj[] = [
  {
    nodeId: '5-LAX1-C11-245_C11Case6Clamshell4o5oz',
    lot: {
      createdAt: '2022-09-02T00:08:11.773Z',
      id: '0c914f7e-4cbe-4a80-96e3-cfde8048e4d0',
      lotName: '5-LAX1-C11-245',
      materialType: 'PACKAGING_LOT',
      product: 'C11',
      properties: {
        farmName: 'LAX1',
        overriddenLtAuthor: 'otapia',
        overriddenLtNotes:
          'Testing a more long string in the notes section to see how is the behavior in the UI in toggle view',
        overriddenLtStatus: PackagingLotTestStatus.FAIL,
        overriddenLtUpdatedAt: '2022-09-02T13:12:37.587Z',
        overriddenQaAuthor: 'otapia',
        overriddenQaNotes:
          'Testing a more long string in the notes section to see how is the behavior in the UI in toggle view',
        overriddenQaStatus: PackagingLotTestStatus.HOLD,
        overriddenQaUpdatedAt: '2022-09-02T13:12:23.751Z',
        packDate: '2022-09-02',
        packageComponents: {
          empty: true,
          traversableAgain: true,
        },
        passedLtStatus: PackagingLotTestStatus.NONE,
        passedQaStatus: PackagingLotTestStatus.NONE,
        releasedAt: null,
        siteName: 'LAX1',
      },
      updatedAt: '2022-09-02T13:12:36.333Z',
    },
    sku: {
      allowedCropNames: ['C11'],
      childSkuName: 'C11Clamshell4o5oz',
      defaultCropName: 'C11',
      description: null,
      displayAbbreviation: 'C11Case6Clamshell4o5oz',
      displayName: 'Sweet Sunrise 6ct Case of Clamshells 4.5oz',
      externalExpirationDays: 10,
      gtin: '10810567030429',
      internalExpirationDays: 4,
      kind: 'sku',
      labelPrimaryColor: '#FED141',
      labelSecondaryColor: '#D50032',
      name: 'C11Case6Clamshell4o5oz',
      netsuiteItem: '5-003-0004-06',
      packagingLotCropCode: 'C11',
      path: 'skus/C11Case6Clamshell4o5oz',
      productName: 'Sweet Sunrise',
      properties: {},
      skuTypeName: 'Case6Clamshell4o5oz',
    },
    count: 1,
    crop: {
      childCrops: [
        {
          allowedCropNames: ['CRC'],
          defaultCropName: 'CRC',
          maxRatio: 1,
          minRatio: 0,
          targetRatio: null,
        },
        {
          allowedCropNames: ['GFF:NPI'],
          defaultCropName: 'GFF:NPI',
          maxRatio: 1,
          minRatio: 0,
          targetRatio: null,
        },
        {
          allowedCropNames: ['GRC'],
          defaultCropName: 'GRC',
          maxRatio: 1,
          minRatio: 0,
          targetRatio: null,
        },
        {
          allowedCropNames: ['BBB:NPI'],
          defaultCropName: 'BBB:NPI',
          maxRatio: 1,
          minRatio: 0,
          targetRatio: null,
        },
      ],
      commonName: 'Unbeetable Blend (AKA Sweet Sunrise)',
      cropTypeName: 'LeafyGreens',
      cultivar: null,
      description: null,
      displayAbbreviation: 'C11',
      displayName: 'Unbeetable Blend (AKA Sweet Sunrise) - C11',
      isSeedable: false,
      media: '',
      name: 'C11',
      path: 'crops/C11',
      properties: {
        plannedGrowDays: 12,
      },
      seedPartNumbers: [],
    },
    expDate: new Date('2022-09-06T07:00:00.000Z'),
    status: FinishedGoodsStatus.EXPIRED,
    releaseDetails: {
      overriddenLtAuthor: 'otapia',
      overriddenLtNotes:
        'Testing a more long string in the notes section to see how is the behavior in the UI in toggle view',
      overriddenLtStatus: PackagingLotTestStatus.FAIL,
      overriddenLtUpdatedAt: '2022-09-02T13:12:37.587Z',
      overriddenQaAuthor: 'otapia',
      overriddenQaNotes:
        'Testing a more long string in the notes section to see how is the behavior in the UI in toggle view',
      overriddenQaStatus: PackagingLotTestStatus.HOLD,
      overriddenQaUpdatedAt: '2022-09-02T13:12:23.751Z',
      passedLtStatus: PackagingLotTestStatus.NONE,
      passedQaStatus: PackagingLotTestStatus.NONE,
      releasedAt: null,
    },
  },
  {
    nodeId: '5-LAX1-C11-219_C11Case6Clamshell4o5oz',
    lot: {
      createdAt: '2022-08-07T00:00:20.052Z',
      id: '54688a82-1a2e-4750-ad09-e7205896e110',
      lotName: '5-LAX1-C11-219',
      materialType: 'PACKAGING_LOT',
      product: 'C11',
      properties: {
        farmName: 'LAX1',
        overriddenLtStatus: PackagingLotTestStatus.NONE,
        overriddenQaStatus: PackagingLotTestStatus.NONE,
        packDate: '2022-08-07',
        passedLtStatus: PackagingLotTestStatus.NONE,
        passedQaStatus: PackagingLotTestStatus.NONE,
        releasedAt: null,
        siteName: 'LAX1',
      },
      updatedAt: '2022-08-07T01:46:06.262Z',
    },
    sku: {
      allowedCropNames: ['C11'],
      childSkuName: 'C11Clamshell4o5oz',
      defaultCropName: 'C11',
      description: null,
      displayAbbreviation: 'C11Case6Clamshell4o5oz',
      displayName: 'Sweet Sunrise 6ct Case of Clamshells 4.5oz',
      externalExpirationDays: 10,
      gtin: '10810567030429',
      internalExpirationDays: 4,
      kind: 'sku',
      labelPrimaryColor: '#FED141',
      labelSecondaryColor: '#D50032',
      name: 'C11Case6Clamshell4o5oz',
      netsuiteItem: '5-003-0004-06',
      packagingLotCropCode: 'C11',
      path: 'skus/C11Case6Clamshell4o5oz',
      productName: 'Sweet Sunrise',
      properties: {},
      skuTypeName: 'Case6Clamshell4o5oz',
    },
    count: 1,
    crop: {
      childCrops: [
        {
          allowedCropNames: ['CRC'],
          defaultCropName: 'CRC',
          maxRatio: 1,
          minRatio: 0,
          targetRatio: null,
        },
        {
          allowedCropNames: ['GFF:NPI'],
          defaultCropName: 'GFF:NPI',
          maxRatio: 1,
          minRatio: 0,
          targetRatio: null,
        },
        {
          allowedCropNames: ['GRC'],
          defaultCropName: 'GRC',
          maxRatio: 1,
          minRatio: 0,
          targetRatio: null,
        },
        {
          allowedCropNames: ['BBB:NPI'],
          defaultCropName: 'BBB:NPI',
          maxRatio: 1,
          minRatio: 0,
          targetRatio: null,
        },
      ],
      commonName: 'Unbeetable Blend (AKA Sweet Sunrise)',
      cropTypeName: 'LeafyGreens',
      cultivar: null,
      description: null,
      displayAbbreviation: 'C11',
      displayName: 'Unbeetable Blend (AKA Sweet Sunrise) - C11',
      isSeedable: false,
      media: '',
      name: 'C11',
      path: 'crops/C11',
      properties: {
        plannedGrowDays: 12,
      },
      seedPartNumbers: [],
    },
    expDate: new Date('2022-08-11T07:00:00.000Z'),
    status: FinishedGoodsStatus.EXPIRED,
    releaseDetails: {
      overriddenLtStatus: PackagingLotTestStatus.NONE,
      overriddenQaStatus: PackagingLotTestStatus.NONE,
      passedLtStatus: PackagingLotTestStatus.NONE,
      passedQaStatus: PackagingLotTestStatus.NONE,
      releasedAt: null,
    },
  },
];
