import { FarmDefSku } from '@plentyag/core/src/farm-def/types';

export const MOCK_FARM_DEF_SKU_RESPONSE: FarmDefSku[] = [
  {
    name: 'E31Clamshell4o5oz',
    kind: 'sku',
    path: 'skus/E31Clamshell4o5oz',
    description: null,
    netsuiteItem: '5-010-0001-04',
    gtin: '00810567030453',
    productName: 'Mizuna Mix',
    displayName: 'Mizuna Mix Clamshell 4.5oz',
    displayAbbreviation: 'E31-Clam4.5oz',
    skuTypeName: 'Clamshell4o5oz',
    packagingLotCropCode: 'E31',
    defaultCropName: 'E31',
    allowedCropNames: ['E31'],
    labelPrimaryColor: '#E64700',
    labelSecondaryColor: '#542E8E',
    internalExpirationDays: 4,
    externalExpirationDays: 11,
    childSkuName: null,
    properties: {},
    brandTypeName: 'Plenty',
    productWeightOz: 4.5,
  },
  {
    name: 'E31Case6Clamshell4o5oz',
    kind: 'sku',
    path: 'skus/E31Case6Clamshell4o5oz',
    description: null,
    netsuiteItem: '5-010-0001-06',
    gtin: '10810567030450',
    productName: 'Mizuna Mix',
    displayName: 'Mizuna Mix Case 6 Clamshell 4.50z',
    displayAbbreviation: 'E31-Case6Clam4.5oz',
    skuTypeName: 'Case6Clamshell4o5oz',
    packagingLotCropCode: 'E31',
    defaultCropName: 'E31',
    allowedCropNames: ['E31'],
    labelPrimaryColor: '#E64700',
    labelSecondaryColor: '#542E8E',
    internalExpirationDays: 4,
    externalExpirationDays: 11,
    childSkuName: 'MizunaMixClamshell4o5oz',
    properties: {},
    caseQuantityPerPallet: 6,
  },
  {
    name: 'B20Clamshell4o5oz',
    kind: 'sku',
    path: 'skus/B20Clamshell4o5oz',
    description: null,
    netsuiteItem: '5-005-0001-04',
    gtin: '00810567030439',
    productName: 'Baby Arugula',
    displayName: 'Baby Arugula Clamshell 4.5oz',
    displayAbbreviation: 'B20-Clam4.5oz',
    skuTypeName: 'Clamshell4o5oz',
    packagingLotCropCode: 'BAC',
    defaultCropName: 'BAC',
    allowedCropNames: ['BAC', 'B20'],
    labelPrimaryColor: '#861F41',
    labelSecondaryColor: '#FFBAC6',
    internalExpirationDays: 4,
    externalExpirationDays: 11,
    childSkuName: null,
    properties: {},
    brandTypeName: 'Plenty',
    productWeightOz: 4,
  },
  {
    name: 'B20Case6Clamshell4o5oz',
    kind: 'sku',
    path: 'skus/B20Case6Clamshell4o5oz',
    description: null,
    netsuiteItem: '5-005-0004-06',
    gtin: '10810567030436',
    productName: 'Baby Arugula',
    displayName: 'Baby Arugula 6ct Case of Clamshells 4.5oz',
    displayAbbreviation: 'B20-Case6Clam4.5oz',
    skuTypeName: 'Case6Clamshell4o5oz',
    packagingLotCropCode: 'BAC',
    defaultCropName: 'BAC',
    allowedCropNames: ['BAC', 'B20'],
    labelPrimaryColor: '#861F41',
    labelSecondaryColor: '#FFBAC7',
    internalExpirationDays: 4,
    externalExpirationDays: 11,
    childSkuName: 'ArugulaClamshell4o5oz',
    properties: {},
    caseQuantityPerPallet: 6,
  },
];
