export const FarmOsModules: FarmOsModule[] = [
  {
    label: 'Admin',
    resource: 'HYP_ADMIN',
    url: '/admin',
    backend: 'hypocotyl',
    react: false,
  },
  {
    label: 'Crops',
    resource: 'HYP_CROPS',
    url: '/crops-skus',
    backend: 'sprout',
    react: true,
  },
  {
    label: 'Derived Observations',
    resource: 'HYP_DERIVED_OBSERVATIONS',
    url: '/derived-observations',
    backend: 'sprout',
    react: true,
    groupUnder: 'Environment V2',
  },
  {
    label: 'Devices v2',
    resource: 'HYP_DEVICES_V2',
    url: '/devices-v2',
    backend: 'sprout',
    react: true,
  },
  {
    label: 'Environment V2',
    resource: 'HYP_ENVIRONMENT_V2',
    url: '/environment-v2',
    backend: 'sprout',
    react: true,
  },
  {
    label: 'Ignition Tag Registry',
    resource: 'HYP_IGNITION_TAG_REGISTRY',
    url: '/ignition-tag-registry',
    backend: 'sprout',
    react: true,
    groupUnder: 'Environment V2',
  },
  {
    label: 'API Docs',
    resource: 'HYP_API_DOCS',
    url: '/api-docs',
    backend: 'sprout',
    react: true,
    groupUnder: 'Docs',
  },
  {
    label: 'Quality',
    resource: 'HYP_QUALITY',
    url: '/quality',
    backend: 'sprout',
    react: true,
    groupUnder: 'Quality',
  },
  {
    label: 'Data Docs',
    resource: 'HYP_DATA_DOCS',
    url: '/data-docs',
    backend: 'sprout',
    react: true,
    groupUnder: 'Docs',
  },
  {
    label: 'Lab Testing',
    resource: 'HYP_LAB_TESTING',
    url: '/lab-testing',
    backend: 'sprout',
    react: true,
  },
  {
    label: 'Perception',
    resource: 'HYP_PERCEPTION',
    url: '/perception',
    backend: 'sprout',
    react: true,
  },
  {
    label: 'Production',
    resource: 'HYP_PRODUCTION',
    url: '/production',
    backend: 'sprout',
    react: true,
  },
  {
    label: 'Production Admin',
    resource: 'HYP_PRODUCTION_ADMIN',
    url: '/production-admin',
    backend: 'sprout',
    react: true,
  },
];
