import { NormalizedObservation } from '@plentyag/core/src/types';

export const mockObservations: NormalizedObservation[] = [
  {
    clientId: 'clientId1',
    containerId: 'containerId1',
    containerLocationRef: 'containerLocationRef1',
    createdAt: 'createdAt1',
    derivedFrom: 'derivedFrom1',
    deviceId: 'deviceId1',
    eventId: 'eventId1',
    eventType: 'eventType1',
    isPrediction: false,
    material: 'material1',
    materialId: 'materialId1',
    materialRegionType: 'materialRegionType1',
    measurementType: 'measurementType1',
    numericValue: false,
    objectId: 'objectId1',
    observationId: 'observationId1',
    observationName: 'SprinkleFaultDetected',
    observedAt: null,
    otherProperties: {
      faults:
        '{\n  "overcurrent_1": true,\n  "overcurrent_2": true,\n  "overcurrent_3": true,\n  "overcurrent_4": true,\n  "overcurrent_5": true,\n  "overcurrent_6": true\n}',
    },
    path: 'path1',
    predictionValidAt: 'predictionValidAt1',
    rawObservation: {},
    units: 'units1',
    valueDataType: 'valueDataType1',
    valueNumeric: null,
    valueString: 'valueString1',
    isNumericValue: false,
  },
  {
    clientId: 'clientId2',
    containerId: 'containerId2',
    containerLocationRef: 'containerLocationRef2',
    createdAt: 'createdAt2',
    derivedFrom: 'derivedFrom2',
    deviceId: 'deviceId2',
    eventId: 'eventId2',
    eventType: 'eventType2',
    isPrediction: false,
    material: 'material2',
    materialId: 'materialId2',
    materialRegionType: 'materialRegionType2',
    measurementType: 'measurementType2',
    numericValue: false,
    objectId: 'objectId2',
    observationId: 'observationId2',
    observationName: 'HathorFaultDetected',
    observedAt: '2022-01-01 01:00:00',
    otherProperties: {
      faults: '{\n  "requestToEnter": true\n}',
    },
    path: 'path2',
    predictionValidAt: 'predictionValidAt2',
    rawObservation: {},
    units: 'units2',
    valueDataType: 'valueDataType2',
    valueNumeric: null,
    valueString: 'valueString2',
    isNumericValue: false,
  },
  {
    clientId: 'clientId3',
    containerId: 'containerId3',
    containerLocationRef: 'containerLocationRef3',
    createdAt: 'createdAt3',
    derivedFrom: 'derivedFrom3',
    deviceId: 'deviceId3',
    eventId: 'eventId3',
    eventType: 'eventType3',
    isPrediction: false,
    material: 'material3',
    materialId: 'materialId3',
    materialRegionType: 'materialRegionType3',
    measurementType: 'measurementType3',
    numericValue: false,
    objectId: 'objectId3',
    observationId: 'observationId3',
    observationName: 'LuminaireOverCurrentFaultEvent',
    observedAt: '2022-01-01 00:00:00',
    otherProperties: {},
    path: 'path3',
    predictionValidAt: 'predictionValidAt3',
    rawObservation: {},
    units: 'units3',
    valueDataType: 'valueDataType3',
    valueNumeric: null,
    valueString: 'valueString3',
    isNumericValue: false,
  },
];
